=== OphidiaBigData/ophidia-analytics-framework/etc/ophidia_dtd/ophidiaprimitive.dtd
<!-- DTD for Ophidia primitives -->

<!ELEMENT primitive (info,args)>
<!ATTLIST primitive name CDATA #REQUIRED>
<!ATTLIST primitive version CDATA #REQUIRED>

<!ELEMENT info (abstract,author,creationdate?,license?,return,operation?)>

<!ELEMENT abstract (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT creationdate (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ATTLIST license url CDATA #REQUIRED>
<!ELEMENT return EMPTY>
<!ATTLIST return type (binary-array|bit-array|string|int|long|long-long|float|double|void) #REQUIRED>
<!ELEMENT operation EMPTY>
<!ATTLIST operation type (id|simple|reduce|aggregate) #REQUIRED>

<!ELEMENT args (argument* | multi-argument*)*>

<!ELEMENT argument (#PCDATA)>
<!ATTLIST argument type (binary-array|bit-array|string|int|long-long|float|double|oph_type|oph_complex_type|oph_operator|numeric|long|bit|bool|oph_bit_op) #REQUIRED>
<!ATTLIST argument minvalue CDATA #IMPLIED>
<!ATTLIST argument maxvalue CDATA #IMPLIED>
<!ATTLIST argument default CDATA #IMPLIED>
<!ATTLIST argument values CDATA #IMPLIED>
<!ATTLIST argument mandatory (yes|no) "yes">

<!ELEMENT multi-argument (#PCDATA)>
<!ATTLIST multi-argument type (string|binary-array|long-long|double|oph_type|oph_complex_type|oph_operator|numeric|int|long|bit|bool|oph_bit_op|bit-array) #REQUIRED>
<!ATTLIST multi-argument minvalue CDATA #IMPLIED>
<!ATTLIST multi-argument maxvalue CDATA #IMPLIED>
<!ATTLIST multi-argument mintimes CDATA #IMPLIED>
<!ATTLIST multi-argument maxtimes CDATA #IMPLIED>
<!ATTLIST multi-argument default CDATA #IMPLIED>
<!ATTLIST multi-argument values CDATA #IMPLIED>
<!ATTLIST multi-argument mandatory (yes|no) "yes">

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_ZONAL_STATS_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_zonal_stats" version="1.0">
    <info>
        <abstract>[Behaviour]
Returns an array in which a zonal statistical metrix has been applied to the matrix represeted by the input array.
        
[Parameters]
- input measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- output measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- measure : input measure.
- buffer : zone size (0 means 1 pixel, 1 means a square of 9 pixels, etc.)
- operator name : type of operator
                  -- &apos;oph_max&apos; : compute the maximum value of a zone (default);
                  -- &apos;oph_min&apos; : compute the minimum value of a zone;
                  -- &apos;oph_avg&apos; : compute the mean of all elements of a zoene;
                  -- &apos;oph_sum&apos; : compute the sum of all elements of a zone.
- missingvalue : value to be considered as missing value; by default it is NAN (for &apos;oph_double&apos; and &apos;oph_float&apos;).
- sampling : flag set in case data have to be sampled on the center of the zone.

[Return type]
Binary-array.
        
[Examples]
oph_zonal_stats(&apos;OPH_DOUBLE&apos;,&apos;OPH_DOUBLE&apos;,measure)</abstract>
        <author>CMCC Foundation</author>
        <category>Transformation</category>
        <creationdate>02/02/2020</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
        <operation type="simple"/>
    </info>
    <args>
		<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">input measure type</argument>
		<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">output measure type</argument>
		<argument type="binary-array" mandatory="yes">measure</argument>
		<argument type="double" mandatory="no" default="0" minvalue="0">buffer</argument>
		<argument type="oph_operator" mandatory="no" default="'oph_max'" values="'oph_max'|'oph_min'|'oph_avg'|'oph_sum'">operator name</argument>
		<argument type="double" mandatory="no" default="NAN">missingvalue</argument>
		<argument type="string" mandatory="no" default="yes" values="yes|no">sampling</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_COUNT_ARRAY_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_count_array" version="1.0">
    <info>
        <abstract>[Behaviour]
Counts the number of elements into an array.

[Parameters]
- input measure type : Ophidia typing. Supported types are:
                 &apos;oph_double&apos;;
                 &apos;oph_float&apos;;
                 &apos;oph_int&apos;;
                 &apos;oph_long&apos;;
                 &apos;oph_short&apos;;
                 &apos;oph_byte&apos;.
- output measure type : not used.
- measure : first input measure.
- include missing values : use '1' (default) to include missing values, use '0' to exclude them.
- missingvalue : value to be considered as missing value; by default it is NAN (for &apos;oph_double&apos; and &apos;oph_float&apos;).

[Return type]
Long-long.
        
[Examples]
oph_count_array(&apos;OPH_FLOAT&apos;,&apos;&apos;,measure)</abstract>
        <author>CMCC Foundation</author>
        <category>Core Array</category>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="long-long"/>
        <operation type="reduce"/>
    </info>
    <args>
		<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">input measure type</argument>
		<argument type="oph_type" mandatory="yes">output measure type</argument>
		<argument type="binary-array" mandatory="yes">measure</argument>
		<argument type="bool" mandatory="no" default="1" values="0|1">include missing values</argument>
		<argument type="double" mandatory="no" default="NAN">missingvalue</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_CCLUSTER_KCLUSTER_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_ccluster_kcluster" version="1.0">
    <info>
        <abstract>[Behaviour]
Compute clusters from input data through the use of k-means or k-medians algorithms.
        
[Parameters]
- input measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- output measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- measure : input measures.
- k : number of requested clusters.
- method : clustering algorithm. Supported algorithms are:
					-- &apos;KMEANS&apos; (default);
					-- &apos;KMEDIANS&apos;.
- level : type of output. Supported outputs are:
                    -- &apos;CENTROIDS&apos; : only centroid values for each cluster (spatial information is lost) (output is oph_double);
                    -- &apos;LABELS&apos; : returns an integer between 0 and k-1 for each point according to found clusters (output is oph_int);
                    -- &apos;ALL&apos; (default) : returns the centroid value of the corresponding cluster for each point (output is oph_double).
- npass : number of iterations for the EM algorithm. At each iteration means or medians are computed and there is
          a new cluster assignment. With more iterations results are more accurate. Default value is 1.

[Return type]
Binary-array.
        
[Examples]
Group data into 2 clusters, with 10 EM iterations, and return the centroid value for each input point.
oph_ccluster_kcluster(&apos;OPH_DOUBLE&apos;,&apos;OPH_DOUBLE&apos;,measure,2,&apos;KMEANS&apos;,10,&apos;ALL&apos;)</abstract>
        <author>CMCC Foundation</author>
        <creationdate>17/06/2014</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
	<operation type="reduce"/>
    </info>
    <args>
	<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'|'oph_complex_double'|'oph_complex_float'|'oph_complex_int'|'oph_complex_long'">input measure type</argument>
        <argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'|'oph_complex_double'|'oph_complex_float'|'oph_complex_int'|'oph_complex_long'">output measure type</argument>
	<argument type="binary-array" mandatory="yes">measure</argument>
	<argument type="int" mandatory="yes">k</argument>
	<argument type="string" mandatory="no" default="'kmeans'" values="'kmeans'|'kmedians'">method</argument>
	<argument type="string" mandatory="no" default="'all'" values="'centroids'|'labels'|'all'">level</argument>
	<argument type="int" mandatory="no" default="1">npass</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_GSL_COMPLEX_TO_RECT_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_gsl_complex_to_rect" version="1.0">
    <info>
        <abstract>[Behaviour]
Converts a binary array of complex numbers expressed in polar form into the rectangular form.

[Parameters]
- input measure type : Ophidia typing. Supported types are:
                         &apos;oph_complex_double&apos;;
                         &apos;oph_complex_float&apos;;
                         &apos;oph_complex_int&apos;;
                         &apos;oph_complex_long&apos;.
- output measure type : Ophidia typing. Supported types are:
                         &apos;oph_complex_double&apos;;
                         &apos;oph_complex_float&apos;;
                         &apos;oph_complex_int&apos;;
                         &apos;oph_complex_long&apos;.
- measure : input measure.

[Return type]
Binary-array.

[Examples]
Get the rectangular form of an array of complex numbers expressed in polar coordinates.
oph_gsl_complex_to_rect(&apos;OPH_COMPlEX_DOUBLE&apos;,&apos;OPH_COMPLEX_DOUBLE&apos;,measure)</abstract>
        <author>CMCC Foundation</author>
        <category>Arithmetic</category>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
        <operation type="simple"/>
    </info>
    <args>
		<argument type="oph_type" mandatory="yes" values="'oph_complex_double'|'oph_complex_float'|'oph_complex_int'|'oph_complex_long'">input measure type</argument>
		<argument type="oph_type" mandatory="yes" values="'oph_complex_double'|'oph_complex_float'|'oph_complex_int'|'oph_complex_long'">output measure type</argument>
		<argument type="binary-array" mandatory="yes">measure</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_MUL_SCALAR2_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_mul_scalar2" version="1.0">
    <info>
        <abstract>[Behaviour]
Multiplies each element of the measure array by a scalar value. It can operate also with complex numbers.
In case of real numbers, it multiplies each element in the input array by scalar value (real) if specified (default is 1).
In case of complex numbers, it multiplies each element in the input array by the complex number with real part equal to scalar value (real) and imaginary part equal to scalar value (imaginary) if available (default is 0).

[Parameters]
- input measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;
					&apos;oph_complex_double&apos;;
					&apos;oph_complex_float&apos;;
					&apos;oph_complex_int&apos;;
					&apos;oph_complex_long&apos;.
- output measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;
					&apos;oph_complex_double&apos;;
					&apos;oph_complex_float&apos;;
					&apos;oph_complex_int&apos;;
					&apos;oph_complex_long&apos;.
- measure : input measure.
- scalar value (real) : in case of real numbers, it is the number to be multiplied by each element of the input measure.
                        In case of complex numbers, it is the real part of the complex number to be multiplied by each element of the input measure.
                        Default is 1.
- scalar value (imaginary) : considered only in case of complex numbers, it is the imaginary part of the complex number to be multiplied by each element of the input measure.
                             Default is 0.

[Return type]
Binary-array.

[Examples]
Multiply by 2+2i each element of the input array.
oph_mul_scalar2(&apos;OPH_COMPLEX_DOUBLE&apos;,&apos;OPH_COMPLEX_DOUBLE&apos;,measure,2,2)</abstract>
        <author>CMCC Foundation</author>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
	<operation type="simple"/>
    </info>
    <args>
	<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'|'oph_complex_double'|'oph_complex_float'|'oph_complex_int'|'oph_complex_long'">input measure type</argument>
	<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'|'oph_complex_double'|'oph_complex_float'|'oph_complex_int'|'oph_complex_long'">output measure type</argument>
	<argument type="binary-array" mandatory="yes">measure</argument>
	<argument type="double" mandatory="no" default="1">scalar value (real)</argument>
	<argument type="double" mandatory="no" default="0">scalar value (imaginary)</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_BIT_REDUCE_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_bit_reduce" version="1.0">
    <info>
        <abstract>[Behaviour]
Execute a bit reduction operation on blocks of count bits.

[Parameters]
- input data type : not used.
- output data type : not used.
- measure : input measure.
- count : aggregation block size.
- operator : type of operation.
             -- &apos;INVALID_BIT_OP&apos; : invalid
             -- &apos;OPH_BIT_AND&apos; : bitwise AND (default)
             -- &apos;OPH_BIT_OR&apos; : bitwise OR
             -- &apos;OPH_BIT_XOR&apos; : bitwise XOR
             -- &apos;OPH_BIT_NAND&apos; : bitwise NAND
             -- &apos;OPH_BIT_NOR&apos; : bitwise NOR
             -- &apos;OPH_BIT_XNOR&apos; : bitwise XNOR
             -- &apos;OPH_BIT_GREATER_THAN&apos; : &gt;
             -- &apos;OPH_BIT_GREATER_OR_EQUAL_TO&apos; : &gt;=
             -- &apos;OPH_BIT_LESS_THAN&apos; : &lt;
             -- &apos;OPH_BIT_LESS_OR_EQUAL_TO&apos; : &lt;=

[Return type]
Bit-array.

[Examples]
OR between all bits in 16-bit groups of bit-measures.
oph_bit_reduce(&apos;&apos;,&apos;&apos;,bit_measure,&apos;OPH_BIT_OR&apos;,16)</abstract>
        <author>CMCC Foundation</author>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="bit-array" />
	<operation type="reduce"/>
    </info>
    <args>
	<argument type="oph_type" mandatory="yes">input data type</argument>
	<argument type="oph_type" mandatory="yes">output data type</argument>
	<argument type="bit-array" mandatory="yes">measure</argument>
	<argument type="oph_bit_op" mandatory="no" default="'OPH_BIT_AND'" values="'INVALID_BIT_OP'|'OPH_BIT_AND'|'OPH_BIT_OR'|'OPH_BIT_XOR'|'OPH_BIT_NAND'|'OPH_BIT_NOR'|'OPH_BIT_XNOR'|'OPH_BIT_GREATER_THAN'|'OPH_BIT_GREATER_OR_EQUAL_TO'|'OPH_BIT_LESS_THAN'|'OPH_BIT_LESS_OR_EQUAL_TO'">operator</argument>
	<argument type="long-long" mandatory="no" default="bit array length">count</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_GSL_SPLINE_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_gsl_spline" version="1.0">
    <info>
        <abstract>[Behaviour]
Computes the interpolation based on cubic splines.

[Parameters]
- input measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- output measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- measure : input measure.
- old_dim : input dimension; data type must be &apos;oph_double&apos;.
- new_dim : new values for dimension; data type must be &apos;oph_double&apos;.

[Return type]
Binary-array.

[Examples]
Compute the interpolation from dimension &apos;x1&apos; to &apos;x2&apos;.
oph_gsl_spline(&apos;OPH_DOUBLE&apos;,&apos;OPH_DOUBLE&apos;,measure,x1,x2)</abstract>
        <author>CMCC Foundation</author>
        <category>Numerical Analysis</category>
        <creationdate>16/07/2015</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
        <operation type="simple"/>
    </info>
    <args>
		<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">input measure type</argument>
		<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">output measure type</argument>
		<argument type="binary-array" mandatory="yes">measure</argument>
		<argument type="binary-array" mandatory="yes">old_dim</argument>
		<argument type="binary-array" mandatory="yes">new_dim</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_INTERLACE_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_interlace" version="1.0">
    <info>
        <abstract>[Behaviour]
Interlaces multiple input measures into a single output measure. It requires at least two measures, otherwise it returns an error. For each measure an input type should be specified. Given two input arrays A(a1, a2, ..., an) and B(b1, b2, ..., bn), the resulting array will be C(a1, b1, a2, b2, ..., an, bn).

[Parameters]
- input measure type : Ophidia typing. Supported types are enumerations of:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- output measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- measure : input measure. This argument can be specified multiple times.

[Return type]
Binary-array.

[Examples]
Interlace three measures
oph_interlace(&apos;OPH_DOUBLE|OPH_FLOAT|OPH_INT&apos;,&apos;OPH_DOUBLE,OPH_FLOAT,OPH_INT&apos;,a.measure,b.measure,c.measure)</abstract>
        <author>CMCC Foundation</author>
        <category>Core Array</category>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
        <operation type="reduce"/>
    </info>
    <args>
		<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'" multivalue="yes">input measure type</argument>
		<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">output measure type</argument>
		<multi-argument type="binary-array" mandatory="yes" mintimes="1">measure</multi-argument>
    </args>
</primitive>
