=== OphidiaBigData/ophidia-analytics-framework/etc/ophidia_dtd/ophidiaprimitive.dtd
<!-- DTD for Ophidia primitives -->

<!ELEMENT primitive (info,args)>
<!ATTLIST primitive name CDATA #REQUIRED>
<!ATTLIST primitive version CDATA #REQUIRED>

<!ELEMENT info (abstract,author,creationdate?,license?,return,operation?)>

<!ELEMENT abstract (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT creationdate (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ATTLIST license url CDATA #REQUIRED>
<!ELEMENT return EMPTY>
<!ATTLIST return type (binary-array|bit-array|string|int|long|long-long|float|double|void) #REQUIRED>
<!ELEMENT operation EMPTY>
<!ATTLIST operation type (id|simple|reduce|aggregate) #REQUIRED>

<!ELEMENT args (argument* | multi-argument*)*>

<!ELEMENT argument (#PCDATA)>
<!ATTLIST argument type (binary-array|bit-array|string|int|long-long|float|double|oph_type|oph_complex_type|oph_operator|numeric|long|bit|bool|oph_bit_op) #REQUIRED>
<!ATTLIST argument minvalue CDATA #IMPLIED>
<!ATTLIST argument maxvalue CDATA #IMPLIED>
<!ATTLIST argument default CDATA #IMPLIED>
<!ATTLIST argument values CDATA #IMPLIED>
<!ATTLIST argument mandatory (yes|no) "yes">

<!ELEMENT multi-argument (#PCDATA)>
<!ATTLIST multi-argument type (string|binary-array|long-long|double|oph_type|oph_complex_type|oph_operator|numeric|int|long|bit|bool|oph_bit_op|bit-array) #REQUIRED>
<!ATTLIST multi-argument minvalue CDATA #IMPLIED>
<!ATTLIST multi-argument maxvalue CDATA #IMPLIED>
<!ATTLIST multi-argument mintimes CDATA #IMPLIED>
<!ATTLIST multi-argument maxtimes CDATA #IMPLIED>
<!ATTLIST multi-argument default CDATA #IMPLIED>
<!ATTLIST multi-argument values CDATA #IMPLIED>
<!ATTLIST multi-argument mandatory (yes|no) "yes">

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_EXPAND_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_expand" version="1.0">
    <info>
        <abstract>[Behaviour]
Returns an array in which each element is copied from input measure if the corresponding element in the array &apos;indexes&apos; is present in the set identified by subset string &apos;start:stride:stop&apos;. If the element is not present then a &apos;filling&apos; item is put.

[Parameters]
- input measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
- output measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
- measure : input measure.
- indexes : input index array used to select data from input measure; lengths of both input arrays should be equal; supported type is only &apos;oph_double&apos;.
- start : index of the first element of output array; if NULL it corresponds to the first index in &apos;indexes&apos;.
- stride : step between successive elements in output array; if NULL it is set to 1.
- stop : index of the last element of output array; if NULL it corresponds to the last index in &apos;indexes&apos;.
- filling : item to be added or operation to be performed in case of empty elements; it can be set to:
            &apos;NAN&apos;, to fill empty elements with NAN (default);
            &apos;interp&apos;, to fill empty elements with the corrsponding value of the set identified by input subset string;
            a real number, to fill empty elements with a number.

[Return type]
Binary-array.
        
[Examples]
Fill monthly data with NAN when time dimension unit is &apos;day&apos;.
oph_expand(&apos;OPH_DOUBLE&apos;,&apos;OPH_DOUBLE&apos;,measure,dimension,NULL,30.4375)</abstract>
        <author>CMCC Foundation</author>
        <creationdate>25/03/2016</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
	<operation type="simple"/>
    </info>
    <args>
	<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'">input measure type</argument>
	<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'">output measure type</argument>
	<argument type="binary-array" mandatory="yes">measure</argument>
	<argument type="binary-array" mandatory="no" default="NULL">indexes</argument>
	<argument type="double" mandatory="no" default="NULL">start</argument>
	<argument type="double" mandatory="no" default="1">stride</argument>
	<argument type="double" mandatory="no" default="NULL">stop</argument>
	<argument type="string" mandatory="no" default="NAN">filling</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_AGGREGATE_OPERATOR_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_aggregate_operator" version="1.0">
    <info>
        <abstract>[Behaviour]
Aggregates different measure arrays performing the specified operation on each column of array elements.

[Parameters]
- input measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- output measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- measure : input measure.
- operator name : type of aggregation.
                -- &apos;oph_count&apos; : compute the number of elements;
                -- &apos;oph_max&apos; : compute the maximum (default);
                -- &apos;oph_min&apos; : compute the minimum;
                -- &apos;oph_avg&apos; : compute the mean;
                -- &apos;oph_sum&apos; : compute the sum.
- missingvalue : value to be considered as missing value; by default it is NAN (for &apos;oph_double&apos; and &apos;oph_float&apos;).

[Return type]
Binary-array.

[Examples]
Compute the mean value.
oph_aggregate_operator(&apos;OPH_DOUBLE&apos;,&apos;OPH_DOUBLE&apos;,measure,&apos;OPH_AVG&apos;)</abstract>
        <author>CMCC Foundation</author>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
	<operation type="aggregate"/>
    </info>
    <args>
	<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">input data type</argument>
	<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">output data type</argument>
	<argument type="binary-array" mandatory="yes">measure</argument>
	<argument type="oph_operator" mandatory="no" default="'oph_max'" values="'oph_count'|'oph_max'|'oph_min'|'oph_avg'|'oph_sum'">operator name</argument>
	<argument type="double" mandatory="no" default="NAN">missingvalue</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_BIT_SHIFT_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_bit_shift" version="1.0">
    <info>
        <abstract>[Behaviour]
Executes a shifting operation of &apos;offset&apos; bits inside the measure array using the &apos;filling&apos; character.

[Parameters]
- input data type : not used.
- output data type : not used.
- measure : input measure.
- offset : specify the number of 1-bit movements.
           If offset&gt;0 then shift to the right.
           If offset&lt;0 then shift to the left.
           Default value (0) corresponds to no shift.
- filling : filling character, 0 (default) or 1.

[Return type]
Bit-array.

[Examples]
Execute a 10-bit shift to the right.
oph_bit_shift(&apos;&apos;,&apos;&apos;,bit_measure,10)</abstract>
        <author>CMCC Foundation</author>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="bit-array" />
	<operation type="simple"/>
    </info>
    <args>
	<argument type="oph_type" mandatory="yes">input data type</argument>
	<argument type="oph_type" mandatory="yes">output data type</argument>
	<argument type="bit-array" mandatory="yes">measure</argument>
	<argument type="long-long" mandatory="no" default="0">offset</argument>
	<argument type="bit" mandatory="no" default="0" values="0|1">filling</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_GSL_STATS_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_gsl_stats" version="1.0">
    <info>
        <abstract>[Behaviour]
Compute statistical indexes of the measure array. The type of indexes depends on a mask.
        
[Parameters]
- input measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- output measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- measure : input measure.
- mask : possible values are
         -- 00000000000000 : invalid
         -- 1xxxxxxxxxxxxx : mean
         -- x1xxxxxxxxxxxx : variance
         -- xx1xxxxxxxxxxx : std dev
         -- xxx1xxxxxxxxxx : abs dev
         -- xxxx1xxxxxxxxx : skew
         -- xxxxx1xxxxxxxx : kurtosis
         -- xxxxxx1xxxxxxx : autocorrelation
         -- xxxxxxx1xxxxxx : max
         -- xxxxxxxx1xxxxx : min
         -- xxxxxxxxx1xxxx : 0.05 quantile
         -- xxxxxxxxxx1xxx : 0.25 quantile ->Q1
         -- xxxxxxxxxxx1xx : 0.5  quantile ->Q2 (median)
         -- xxxxxxxxxxxx1x : 0.75 quantile ->Q3
         -- xxxxxxxxxxxxx1 : 0.95 quantile
         -- 11111111111111 : all (default)
         -- 101            : mean + std dev
         -- â€¦
        
[Return type]
Binary-array.
        
[Examples]
Compute the mean and the standard deviation of input measures.
oph_gsl_stats(&apos;OPH_DOUBLE&apos;,&apos;OPH_DOUBLE&apos;,measure,&apos;101&apos;)</abstract>
        <author>CMCC Foundation</author>
        <category>Statistical</category>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
        <operation type="reduce"/>
    </info>
    <args>
		<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">input measure type</argument>
		<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">output measure type</argument>
		<argument type="binary-array" mandatory="yes">measure</argument>
		<argument type="string" mandatory="no" default="11111111111111">mask</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_GET_SUBARRAY3_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_get_subarray3" version="1.0">
    <info>
        <abstract>[Behaviour]
Extract a subset of a measures array. If size-i params are defined then the array is considered multidimensional 
with i implicit dimensions, each of size-i. The subset can also be applied on multpile dimensions.

[Parameters]
- input measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- output measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- measure : input measure.
- subset : enumeration of comma-separated elementary filters (1 series of filters for each dimension). Possible filter forms:
            -- start_index : select a single value, specified by its index
            -- start_index:stop_index : select elements from start_index to stop_index
            -- start_index:stride:stop_index : select elements from start_index to stop_index with a step of stride
            Indexes are integers from 1 to the dimension size and it can be used &quot;end&quot; to specify
            the index of the last element.
- block size : product of slowly changing dimensions.
- size : size of the dimension on which subsetting is done.

[Return type]
Binary-array.

[Examples]
Extract elements 1 and 2 with block size 360 and size 100.
oph_get_subarray3(&apos;OPH_DOUBLE&apos;,&apos;OPH_DOUBLE&apos;,measure,&apos;1,2&apos;,360,100)</abstract>
        <author>CMCC Foundation</author>
        <category>Selection</category>
        <creationdate>01/10/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
        <operation type="simple"/>
    </info>
    <args>
		<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">input measure type</argument>
		<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">output measure type</argument>
		<argument type="binary-array" mandatory="yes">measure</argument>
		<multi-argument type="string" mandatory="no" default="1:end" mintimes="0">subset</multi-argument>
		<multi-argument type="long-long" mandatory="no" default="1" mintimes="0">block size</multi-argument>
		<multi-argument type="long-long" mandatory="no" default="0" mintimes="0">size</multi-argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_COMPARE_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_compare" version="1.0">
    <info>
        <abstract>[Behaviour]
Return 0 if the two input measures are equal.

[Parameters]
- input measure type : not used.
- output measure type : not used.
- measure a : first input measure.
- measure b : second input measure.

[Return type]
Long-long.
        
[Examples]
oph_compare(&apos;&apos;,&apos;&apos;,measure_a,measure_b)</abstract>
        <author>CMCC Foundation</author>
        <category>Arithmetic</category>
        <creationdate>24/09/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="long-long" />
        <operation type="simple"/>
    </info>
    <args>
		<argument type="oph_type" mandatory="yes">input measure type</argument>
		<argument type="oph_type" mandatory="yes">output measure type</argument>
		<argument type="binary-array" mandatory="yes">measure a</argument>
		<argument type="binary-array" mandatory="yes">measure b</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_FILTER_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_filter" version="1.0">
    <info>
        <abstract>[Behaviour]
It applies a filtering on the time series in the measure array. The filter is applied by first transforming in the frequency-domain with the FFT functions from GSL and then retransforming in the time-domain with the inverse function. 
The filter can be of 4 different types: lowpass, highpass, bandpass and notch. 
Measures can be OPH_INTs, OPH_LONGs, OPH_FLOATs, OPH_DOUBLEs, OPH_COMPLEX_INTs, OPH_COMPLEX_LONGs, OPH_COMPLEX_FLOATs or OPH_COMPLEX_DOUBLEs.
The output type will be OPH_DOUBLE (for real input measures) or OPH_COMPLEX_DOUBLE (for complex input measures).
Cut frequencies can only be positive numbers within the range 0 to 0.5

[Parameters]
- input measure type : Ophidia typing. Supported types are:
					&apos;oph_int&apos;;
					&apos;oph_long&apos;;
					&apos;oph_float&apos;;
					&apos;oph_double&apos;;
					&apos;oph_complex_int&apos;;
					&apos;oph_complex_long&apos;;
					&apos;oph_complex_float&apos;;
					&apos;oph_complex_double&apos;.
- output measure type : Ophidia typing. Supported types are:
                                        &apos;oph_double&apos;;
                                        &apos;oph_complex_double&apos;.
- measure : input measure.
- filter type: string that represents the type of filter:
			    -- LPF: lowpass filter
                            -- HPF: highpass filter 
			    -- BPF: bandpass filter
                            -- BSF: notch filter 
- cut_frequency1 : cutoff frequency to filter data. It is used for all filters.
- cut_frequency2 : additional cutoff frequency used for bandpass and notch filters where a frequency range is needed.
                 
[Return type]
Binary-array.

[Examples]
Apply the lowpass filter with cut frequency 0.01.
oph_filter(&apos;OPH_INT&apos;,&apos;OPH_DOUBLE&apos;,measure, 'LPF', 0.01)</abstract>
        <author>CMCC Foundation</author>
        <category>Transformation</category>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
        <operation type="simple"/>
    </info>
    <args>
		<argument type="oph_type" mandatory="yes" values="'oph_int'|'oph_long'|'oph_float'|'oph_double'|'oph_complex_int'|'oph_complex_long'|'oph_complex_float'|'oph_complex_double'">input measure type</argument>
		<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_complex_double'">output measure type</argument>
		<argument type="binary-array" mandatory="yes">measure</argument>
		<argument type="string" mandatory="yes" values="'LPF'|'HPF'|'BPF'|'BSF'">filter_type</argument>
                <argument type="double" mandatory="yes">cut_frequency1</argument>
		<argument type="double" mandatory="no">cut_frequency2</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_CONCAT_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_concat" version="1.0">
    <info>
        <abstract>[Behaviour]
Builds a new measure array concatenating the measures specified.

[Parameters]
- input measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- output measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- measure : list of input measures.

[Return type]
Binary-array.

[Examples]
Concatenate measures 60-90 to measures 1-30.
oph_concat(&apos;OPH_DOUBLE|OPH_DOUBLE&apos;,&apos;&apos;,oph_get_subarray(&apos;OPH_DOUBLE&apos;,&apos;&apos;,measure,1,30),oph_get_subarray(&apos;OPH_DOUBLE&apos;,&apos;&apos;,measure,60,31))</abstract>
        <author>CMCC Foundation</author>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
	<operation type="simple"/>
    </info>
    <args>
        <multi-argument type="oph_type" mandatory="yes" default="'oph_double'" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">input measure type</multi-argument>
        <argument type="oph_type" mandatory="yes" default="'oph_double'" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">output measure type</argument>
	<multi-argument type="binary-array" mandatory="yes">measure</multi-argument>
    </args>
</primitive>
