=== OphidiaBigData/ophidia-analytics-framework/etc/ophidia_dtd/ophidiaoperator.dtd
<!-- DTD for Ophidia operators -->

<!ELEMENT operator (info,args)>
<!ATTLIST operator name CDATA #REQUIRED>
<!ATTLIST operator version CDATA #REQUIRED>

<!ELEMENT info (abstract,author,creationdate?,license?,permission?)>

<!ELEMENT abstract (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT creationdate (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ATTLIST license url CDATA #REQUIRED>
<!ELEMENT permission (#PCDATA)>

<!ELEMENT args (argument*)>

<!ELEMENT argument (#PCDATA)>
<!ATTLIST argument type (char|string|int|real|date) #REQUIRED>
<!ATTLIST argument minvalue CDATA #IMPLIED>
<!ATTLIST argument maxvalue CDATA #IMPLIED>
<!ATTLIST argument default CDATA #IMPLIED>
<!ATTLIST argument values CDATA #IMPLIED>
<!ATTLIST argument mandatory (yes|no) "yes">

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_CDO_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_CDO" version="1.0">
    <info>
        <abstract>[Type]
General.

[Behaviour]
It executes a bash script.
The script can eventually process some environmental variables passed by the operator:
- OPH_CDO_DATA_PATH : points to base folder of data repository on server (if available)
- OPH_CDO_SESSION_PATH : points to &lt;oph_web_server_location&gt;/sessions/&lt;session_code&gt;/export/misc
- OPH_CDO_SESSION_URL : points to &lt;oph_web_server&gt;/sessions/&lt;session_code&gt;/export/misc
- OPH_CDO_SESSION_CODE : is the &lt;session_code&gt;
- OPH_CDO_WORKFLOW_ID : is the workflow identifier
- OPH_CDO_MARKER_ID : is the marker identifier associated with the job
- OPH_CDO_SERVER_HOST : is the IP address or DNS name of the host where Ophidia Server is running
- OPH_CDO_SERVER_PORT : is the port number associated with Ophidia Server
- OPH_CDO_USER : is the submitter identifier

[Parameters]
- command : command to be executed; it must be set.
- args : list of pipe-separated arguments to be passed to the command.
- space : set to &quot;yes&quot; in case white spaces belong to arguments;
          set to &quot;no&quot; in case white spaces are separators like &quot;|&quot; (default).
- input : list of input files; it is an additional argument appended to &quot;args&quot;.
- output : list of output files; it is an additional argument appended to &quot;input&quot;.
- cdd : absolute path corresponding to the current directory on data repository.
- force : flag used to force file creation. An existant file is overwritten with &quot;yes&quot; whereas
          the file is created only if it does not exist with &quot;no&quot; (default).
- skip_output : set this flag to &quot;yes&quot; in case no output file has to be created (disabled by default).
- multiple_output : set this flag to &quot;yes&quot; in case more than one output file has to be created (disabled by default);
                    if enabled, output file names are discovered by listing output folder.
- stdout : file where stdout will be redirected (appended) or &quot;stdout&quot; for no redirection.
- stderr : file where stderr will be redirected (appended) or &quot;stderr&quot; for no redirection.

[System parameters]
- exec_mode : operator execution mode. Possible values are async (default) for
              asynchronous mode, sync for synchronous mode with json-compliant output.
- ncores : number of parallel processes to be used (min. 1).
           This operator is not parallel, so the only possible value is 1.
- nthreads : number of parallel threads per process to be used (min. 1).
- sessionid : session identifier used server-side to manage sessions and jobs.
              Usually users don't need to use/modify it, except when it is necessary
              to create a new session or switch to another one.
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
                  cdo_output : show the output of the command;
                  cdo_returncode : show the return code of the command.

[Examples]
Execute the command &quot;cdo -selname,tas infile outfile&quot; without redirecting stdout and stderr:
OPH_TERM: oph_cdo command=-selname,tas;args=infile|outfile;
SUBMISSION STRING: &quot;operator=oph_cdo;command=-selname,tas;args=infile|outfile;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Data Analysis</category>
        <creationdate>23/06/2020</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>execute</permission>
    </info>
    <args>
		<argument type="string" mandatory="yes">command</argument>
		<argument type="string" mandatory="no" default="" multivalue="yes">args</argument>
		<argument type="string" mandatory="no" default="no" values="yes|no">space</argument>
		<argument type="string" mandatory="no" default="none" multivalue="yes">input</argument>
		<argument type="string" mandatory="no" default="none" multivalue="yes">output</argument>
		<argument type="string" mandatory="no" default="no" values="yes|no">skip_output</argument>
		<argument type="string" mandatory="no" default="no" values="yes|no">multiple_output</argument>
		<argument type="string" mandatory="no" default="/">cdd</argument>
		<argument type="string" mandatory="no" default="no" values="yes|no">force</argument>
		<argument type="string" mandatory="no" default="stdout">stdout</argument>
		<argument type="string" mandatory="no" default="stderr">stderr</argument>
		<argument type="string" mandatory="no" default="async" values="async|sync">exec_mode</argument>
		<argument type="string" mandatory="no" default="null">sessionid</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1" maxvalue="1">ncores</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1">nthreads</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|cdo_output|cdo_returncode">objkey_filter</argument>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_ENDIF_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_ENDIF" version="1.0">
    <info>
        <abstract>[Type]
Flow control.

[Behaviour]
Close a selection block &quot;if&quot;.
      
</abstract>
        <author>CMCC Foundation</author>
        <creationdate>20/06/2016</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
	<permission>read</permission>
    </info>
    <args>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_MOVECONTAINER_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_MOVECONTAINER" version="1.0">
    <info>
        <abstract>[Type]
Data Process.

[Behaviour]
It moves/renames a visible container.

[Parameters]
- container : exactly 2 paths (separated by |) for the input and the output containers (with this ordering) must be specified.
                    Paths can be relative to the cwd or absolute.
                    In case of moving operation without renaming, it is necessary to re-specify
                    the name of the input container.
- cwd : absolute path corresponding to the current working directory.
        The user can operate only within his folders/containers.

[System parameters]    
- exec_mode : operator execution mode. Possible values are async (default) for
              asynchronous mode, sync for synchronous mode with json-compliant output.
- ncores : number of parallel processes to be used (min. 1).
           This operator is not parallel, so the only possible value is 1.
- sessionid : session identifier used server-side to manage sessions and jobs.
              Usually users don't need to use/modify it, except when it is necessary
              to create a new session or switch to another one.
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
                  movecontainer : no output.
        
[Examples]       
Move and rename the visible container &quot;container1&quot; from &quot;/session-code1/folder1&quot; to &quot;/session-code1/folder1/folder2/container2&quot;:
OPH_TERM: oph_movecontainer container=folder1/container1|folder1/folder2/container2;cwd=/session-code1;
SUBMISSION STRING: &quot;operator=oph_movecontainer;container=folder1/container1|folder1/folder2/container2;cwd=/session-code1;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Virtual File System</category>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>write</permission>
    </info>
    <args>
		<argument type="string" mandatory="yes">container</argument>
		<argument type="string" mandatory="yes">cwd</argument>
		<argument type="string" mandatory="no" default="async" values="async|sync">exec_mode</argument>
		<argument type="string" mandatory="no" default="null">sessionid</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1" maxvalue="1">ncores</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|movecontainer">objkey_filter</argument>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_CLUSTER_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_CLUSTER" version="1.0">
    <info>
        <abstract>[Type]
Management.

[Behaviour]
Start and stop a cluster of I/O servers.

[Parameters]
- action : use one of the following types:
	&quot;start&quot;: try to reserve hosts and starts I/O servers (default);
	&quot;stop&quot;: stop reservation and I/O servers.
- nhosts : number of hosts to be reserved as well as number of I/O servers to be started over them.
- host_partition : name of user-defined partition to be used to group hosts.

[System parameters]
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
                  cancel : show result data as text.
        
[Examples]       
Start 3 I/O servers:
OPH_TERM: oph_cluster nhosts=3;host_partition=cluster;
SUBMISSION STRING: &quot;operator=oph_io_server;nhosts=3;host_partition=cluster;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Administration</category>
        <creationdate>16/03/2018</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>read</permission>
    </info>
    <args>
		<argument type="string" mandatory="yes">host_partition</argument>
		<argument type="string" mandatory="no" default="start" values="start|stop">type</argument>
		<argument type="int" mandatory="no" minvalue="0" default="0">nhosts</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|io_server">objkey_filter</argument>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_GENERIC_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_GENERIC" version="1.0">
    <info>
        <abstract>[Type]
General.

[Behaviour]
It executes a bash script.
The script can eventually process some environmental variables passed by the operator:
- OPH_GENERIC_DATA_PATH : points to base folder of data repository on server (if available)
- OPH_GENERIC_SESSION_PATH : points to &lt;oph_web_server_location&gt;/sessions/&lt;session_code&gt;/export/misc
- OPH_GENERIC_SESSION_URL : points to &lt;oph_web_server&gt;/sessions/&lt;session_code&gt;/export/misc
- OPH_GENERIC_SESSION_CODE : is the &lt;session_code&gt;
- OPH_GENERIC_WORKFLOW_ID : is the workflow identifier
- OPH_GENERIC_MARKER_ID : is the marker identifier associated with the job
- OPH_GENERIC_SERVER_HOST : is the IP address or DNS name of the host where Ophidia Server is running
- OPH_GENERIC_SERVER_PORT : is the port number associated with Ophidia Server
- OPH_GENERIC_USER : is the submitter identifier

[Parameters]
- command : command to be executed; it must be set.
- args : list of pipe-separated arguments to be passed to the command.
- space : set to &quot;yes&quot; in case white spaces belong to arguments;
          set to &quot;no&quot; in case white spaces are separators like &quot;|&quot; (default).
- output_path : absolute path of the output file. By default the file will be saved in current directory on data repository (see &quot;cdd&quot;).
- output_name : filename of the output file. A random value is set by default.
- input : additional argument appended to &quot;args&quot;.
- output : alias for the pair &quot;output_path&quot; and &quot;output_name&quot;; the values of these arguments will be overwritten.
- cdd : absolute path corresponding to the current directory on data repository.
- force : flag used to force file creation. An existant file is overwritten with &quot;yes&quot; whereas
          the file is created only if it does not exist with &quot;no&quot; (default).
- stdout : file where stdout will be redirected (appended) or &quot;stdout&quot; for no redirection.
- stderr : file where stderr will be redirected (appended) or &quot;stderr&quot; for no redirection.

[System parameters]
- exec_mode : operator execution mode. Possible values are async (default) for
              asynchronous mode, sync for synchronous mode with json-compliant output.
- ncores : number of parallel processes to be used (min. 1).
           This operator is not parallel, so the only possible value is 1.
- sessionid : session identifier used server-side to manage sessions and jobs.
              Usually users don't need to use/modify it, except when it is necessary
              to create a new session or switch to another one.
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
                  generic_output : show the output of the command;
                  generic_returncode : show the return code of the command.

[Examples]
Execute the command &quot;cp infile outfile&quot; without redirecting stdout and stderr:
OPH_TERM: oph_generic command=-selname,tas;args=infile|outfile;
SUBMISSION STRING: &quot;operator=oph_generic;command=cp;args=infile|outfile;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Data Analysis</category>
        <creationdate>28/09/2020</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>execute</permission>
    </info>
    <args>
		<argument type="string" mandatory="yes">command</argument>
		<argument type="string" mandatory="no" default="" multivalue="yes">args</argument>
		<argument type="string" mandatory="no" default="no" values="yes|no">space</argument>
		<argument type="string" mandatory="no" default="default">output_path</argument>
		<argument type="string" mandatory="no" default="default">output_name</argument>
		<argument type="string" mandatory="no" default="">input</argument>
		<argument type="string" mandatory="no" default="">output</argument>
		<argument type="string" mandatory="no" default="/">cdd</argument>
		<argument type="string" mandatory="no" default="no" values="yes|no">force</argument>
		<argument type="string" mandatory="no" default="stdout">stdout</argument>
		<argument type="string" mandatory="no" default="stderr">stderr</argument>
		<argument type="string" mandatory="no" default="async" values="async|sync">exec_mode</argument>
		<argument type="string" mandatory="no" default="null">sessionid</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1" maxvalue="1">ncores</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|generic_output|generic_returncode">objkey_filter</argument>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_DELETECONTAINER_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_DELETECONTAINER" version="1.0">
    <info>
        <abstract>[Type]
Data Process.

[Behaviour]
It removes a container with related dimensions and grids. The container can be deleted logically or physically.

[Parameters]
- container : name of the input container.
- cwd : absolute path corresponding to the current working directory
- force : flag used to force the removal of a non-empy container.
          Note that with &quot;yes&quot; all datacubes inside the container will be deleted,
          whereas with &quot;no&quot; (default) the container will be removed only if it is already empty.
- container_pid : PID of the input container. If it is set, &apos;container&apos; and &apos;cwd&apos; are negleted.

[System parameters]    
- exec_mode : operator execution mode. Possible values are async (default) for
              asynchronous mode, sync for synchronous mode with json-compliant output.
- ncores : number of parallel processes to be used (min. 1).
           This operator is not parallel, so the only possible value is 1.
- nthreads : maximum number of parallel threads to be used (min. 1). Used only when the force argument is set to &quot;yes&quot; 
- sessionid : session identifier used server-side to manage sessions and jobs.
              Usually users don't need to use/modify it, except when it is necessary
              to create a new session or switch to another one.
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
                  deletecontainer : no output.
        
[Examples]       
Logically remove the empty visible container &quot;container1&quot; :
OPH_TERM: oph_deletecontainer container=container1;cwd=/session-code;
SUBMISSION STRING: &quot;operator=oph_deletecontainer;container=container1;cwd=/session-code;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Virtual File System</category>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>write</permission>
    </info>
    <args>
		<argument type="string" mandatory="yes">container</argument>
		<argument type="string" mandatory="yes">cwd</argument>
		<argument type="string" mandatory="no" default="-">container_pid</argument>
		<argument type="string" mandatory="no" default="no" values="yes|no">force</argument>
		<argument type="string" mandatory="no" default="async" values="async|sync">exec_mode</argument>
		<argument type="string" mandatory="no" default="null">sessionid</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1" maxvalue="1">ncores</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1">nthreads</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|deletecontainer">objkey_filter</argument>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_MOVECUBE_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_MOVECUBE" version="1.0">
    <info>
        <abstract>[Type]
Data Process.

[Behaviour]
It moves a cube to another folder.

[Parameters]
- cube : target cube.
- path : destination path, which can be relative to the cwd or absolute.
- cwd : absolute path corresponding to the current working directory.
        The user can operate only within his folders/containers.

[System parameters]    
- exec_mode : operator execution mode. Possible values are async (default) for
              asynchronous mode, sync for synchronous mode with json-compliant output.
- ncores : number of parallel processes to be used (min. 1).
           This operator is not parallel, so the only possible value is 1.
- sessionid : session identifier used server-side to manage sessions and jobs.
              Usually users don't need to use/modify it, except when it is necessary
              to create a new session or switch to another one.
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
                  movecontainer : no output.
        
[Examples]       
Move the datacube identified by the PID &quot;http://www.example.com/1/1&quot; to folder &quot;newfolder&quot;
OPH_TERM: oph_movecube cube=http://www.example.com/1/1;path=newfolder;cwd=/session-code1;
SUBMISSION STRING: &quot;operator=oph_movecube;cube=http://www.example.com/1/1;path=newfolder;cwd=/session-code1;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Virtual File System</category>
        <creationdate>28/02/2019</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>write</permission>
    </info>
    <args>
		<argument type="string" mandatory="yes" multivalue="yes">cube</argument>
		<argument type="string" mandatory="no" default="-">path</argument>
		<argument type="string" mandatory="yes">cwd</argument>
		<argument type="string" mandatory="no" default="async" values="async|sync">exec_mode</argument>
		<argument type="string" mandatory="no" default="null">sessionid</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1" maxvalue="1">ncores</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|movecontainer">objkey_filter</argument>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_GET_CONFIG_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_GET_CONFIG" version="1.0">
    <info>
        <abstract>[Type]
Metadata Access

[Behaviour]
Request the configuration parameters.

[Parameters]
- key : name of the metadata to be request.

[System parameters]
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
                  get_config : show config data as text.
        
[Examples]       
Get the URL where XML documents associated with Ophidia operators are located:
OPH_TERM: oph_get_config key=OPH_XML_URL;
SUBMISSION STRING: &quot;operator=oph_get_config;key=OPH_XML_URL;&quot;</abstract>
        <author>CMCC Foundation</author>
        <creationdate>09/03/2014</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
	<permission>read</permission>
    </info>
    <args>
		<argument type="string" mandatory="no" default="all" values="all|OPH_XML_URL|OPH_SESSION_ID|OPH_EXEC_MODE|OPH_NCORES|OPH_DATACUBE|OPH_CWD|OPH_CDD|OPH_BASE_SRC_PATH">key</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|get_config">objkey_filter</argument>
    </args>
</operator>
