=== OphidiaBigData/ophidia-analytics-framework/etc/ophidia_dtd/ophidiaprimitive.dtd
<!-- DTD for Ophidia primitives -->

<!ELEMENT primitive (info,args)>
<!ATTLIST primitive name CDATA #REQUIRED>
<!ATTLIST primitive version CDATA #REQUIRED>

<!ELEMENT info (abstract,author,creationdate?,license?,return,operation?)>

<!ELEMENT abstract (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT creationdate (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ATTLIST license url CDATA #REQUIRED>
<!ELEMENT return EMPTY>
<!ATTLIST return type (binary-array|bit-array|string|int|long|long-long|float|double|void) #REQUIRED>
<!ELEMENT operation EMPTY>
<!ATTLIST operation type (id|simple|reduce|aggregate) #REQUIRED>

<!ELEMENT args (argument* | multi-argument*)*>

<!ELEMENT argument (#PCDATA)>
<!ATTLIST argument type (binary-array|bit-array|string|int|long-long|float|double|oph_type|oph_complex_type|oph_operator|numeric|long|bit|bool|oph_bit_op) #REQUIRED>
<!ATTLIST argument minvalue CDATA #IMPLIED>
<!ATTLIST argument maxvalue CDATA #IMPLIED>
<!ATTLIST argument default CDATA #IMPLIED>
<!ATTLIST argument values CDATA #IMPLIED>
<!ATTLIST argument mandatory (yes|no) "yes">

<!ELEMENT multi-argument (#PCDATA)>
<!ATTLIST multi-argument type (string|binary-array|long-long|double|oph_type|oph_complex_type|oph_operator|numeric|int|long|bit|bool|oph_bit_op|bit-array) #REQUIRED>
<!ATTLIST multi-argument minvalue CDATA #IMPLIED>
<!ATTLIST multi-argument maxvalue CDATA #IMPLIED>
<!ATTLIST multi-argument mintimes CDATA #IMPLIED>
<!ATTLIST multi-argument maxtimes CDATA #IMPLIED>
<!ATTLIST multi-argument default CDATA #IMPLIED>
<!ATTLIST multi-argument values CDATA #IMPLIED>
<!ATTLIST multi-argument mandatory (yes|no) "yes">

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_PREDICATE3_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_predicate3" version="1.0">
    <info>
        <abstract>[Behaviour]
Evaluates a predicate3. For each item of input array, if &apos;condition&apos; is met then &apos;expression1&apos; is executed, else &apos;expression2&apos; is executed.

[Parameters]
- input measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- output measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- measure : input measure.
- condition : condition to be verified. Any boolean expression is acceptable.
- expression 1 : expression executed if condition is met.
- expression 2 : expression executed if condition is not met.
- occurrence : if is set to a number &apos;n&apos; then expression 1 is evaluated only for the &apos;n&apos;-th of the condition; otherwise the expression 2 is evaluated.
               Use &apos;first&apos; or &apos;begin&apos; for the first occurrence.
               Use &apos;last&apos; or &apos;end&apos; for the last occurrence.
               Use &apos;all&apos; to skip this check (defualt).
                 
[Return type]
Binary-array.

[Examples]
Extract measures with temperature values greater than 300 K.
oph_predicate3(&apos;OPH_DOUBLE&apos;,&apos;OPH_DOUBLE&apos;,measure,&apos;x&gt;300&apos;,&apos;1&apos;,&apos;0&apos;)</abstract>
        <author>CMCC Foundation</author>
        <category>Transformation</category>
        <creationdate>12/02/2016</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
        <operation type="simple"/>
    </info>
    <args>
		<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">input measure type</argument>
		<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">output measure type</argument>
		<argument type="binary-array" mandatory="yes">measure</argument>
		<argument type="string" mandatory="yes">condition</argument>
		<argument type="string" mandatory="yes">expression 1</argument>
		<argument type="string" mandatory="yes">expression 2</argument>
		<argument type="string" mandatory="no" default="all">occurrence</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_BIT_SIZE_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_bit_size" version="1.0">
    <info>
        <abstract>[Behaviour]
Computes the size of the bit measure. This is the smallest multiple number of 8 bigger or equal than the bit measure.

[Parameters]
- input data type : not used.
- output data type : not used.
- measure : input measure.

[Return type]
Long-long.
        
[Examples]
oph_bit_size(&apos;&apos;,&apos;&apos;,measure)</abstract>
        <author>CMCC Foundation</author>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="long-long" />
	<operation type="reduce"/>
    </info>
    <args>
	<argument type="oph_type" mandatory="yes">input data type</argument>
	<argument type="oph_type" mandatory="yes">output data type</argument>
	<argument type="bit-array" mandatory="yes">measure</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_REDUCE2_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_reduce2" version="1.0">
    <info>
        <abstract>[Behaviour]
Reduces a measure array performing the specified operation on blocks of count elements. It supports multiple implicit dimension.
        
[Parameters]
- input measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- output measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- measure : input measure.
- operator name : type of operator:
                  -- &apos;oph_count&apos; : compute the number of actual values (not missing);
                  -- &apos;oph_max&apos; : compute the maximum (default);
                  -- &apos;oph_min&apos; : compute the minimum;
                  -- &apos;oph_avg&apos; : compute the mean;
                  -- &apos;oph_sum&apos; : compute the sum;
                  -- &apos;oph_std&apos; : compute the standard deviation;
                  -- &apos;oph_var&apos; : compute the variance;
                  -- &quot;oph_cmoment&quot; : compute the central moment;
                  -- &quot;oph_acmoment&quot; : compute the absolute central moment;
                  -- &quot;oph_rmoment&quot; : compute the raw moment;
                  -- &quot;oph_armoment&quot; : compute the absolute raw moment;
                  -- &quot;oph_quantile&quot; : compute the quantile.
- count : number of elements to be reduced. Default value (0) corresponds to the entire array.
- block size : product of the dimensions that vary more quickly than the dimension to be reduced.
- size : size of the dimension to be reduced. Default value (0) corresponds to the entire array.
- order : order used in evaluation the moments or value of the quantile in range [0, 1].
                  
[Return type]
Binary-array.
        
[Examples]
Reduces a measure array computing the mean on groups of 10 elements with the internal dimension of size 15 and the external
to-be-reduced one of size 10.
oph_reduce2(&apos;OPH_DOUBLE&apos;,&apos;OPH_DOUBLE&apos;,measure,&apos;OPH_AVG&apos;,1,10,15,10)</abstract>
        <author>CMCC Foundation</author>
        <creationdate>04/10/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
	<operation type="reduce"/>
    </info>
    <args>
	<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">input measure type</argument>
	<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">output measure type</argument>
	<argument type="binary-array" mandatory="yes">measure</argument>
	<argument type="oph_operator" mandatory="no" default="'oph_max'" values="'oph_count'|'oph_max'|'oph_min'|'oph_avg'|'oph_sum'|'oph_std'|'oph_var'|'oph_cmoment'|'oph_acmoment'|'oph_rmoment'|'oph_armoment'">operator name</argument>
	<argument type="double" mandatory="no" default="0" minvalue="0" maxvalue="array length">count</argument>
	<argument type="long-long" mandatory="no" default="1" minvalue="1" maxvalue="array length">block size</argument>
	<argument type="long-long" mandatory="no" default="0" minvalue="0" maxvalue="array length">size</argument>
	<argument type="double" mandatory="no" default="2" minvalue="0">order</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_OPERATOR_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_operator" version="1.0">
    <info>
        <abstract>[Behaviour]
Applies an operator on the whole measure array.

[Parameters]
- input measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- output measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- measure : input measure.
- operator name : type of operator
                    -- &apos;oph_count&apos; : compute the number of actual values (not missing);
                    -- &apos;oph_max&apos; : compute the maximum (default);
                    -- &apos;oph_min&apos; : compute the minimum;
                    -- &apos;oph_avg&apos; : compute the mean of all elements;
                    -- &apos;oph_sum&apos; : compute the sum of all elements;
                    -- &apos;oph_std&apos; : compute the standard deviation;
                    -- &quot;oph_cmoment&quot; : compute the central moment;
                    -- &quot;oph_acmoment&quot; : compute the absolute central moment;
                    -- &quot;oph_rmoment&quot; : compute the raw moment;
                    -- &quot;oph_armoment&quot; : compute the absolute raw moment;
                    -- &quot;oph_quantile&quot; : compute the quantile.
- hierarchy : it defines a hierarchy [not used].
- order : order used in evaluation the moments or value of the quantile in range [0, 1].

[Return type]
Binary-array.
        
[Examples]
Compute the mean of all elements.
oph_operator(&apos;OPH_DOUBLE&apos;,&apos;OPH_DOUBLE&apos;,measure,&apos;OPH_AVG&apos;)</abstract>
        <author>CMCC Foundation</author>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
	<operation type="reduce"/>
    </info>
    <args>
	<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">input measure type</argument>
	<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">output measure type</argument>
	<argument type="binary-array" mandatory="yes">measure</argument>
	<argument type="oph_operator" mandatory="no" default="'oph_max'" values="'oph_count','oph_max'|'oph_min'|'oph_avg'|'oph_sum'|'oph_std'|'oph_cmoment'|'oph_acmoment'|'oph_rmoment'|'oph_armoment'">operator name</argument>
	<argument type="string" mandatory="no" default="'oph_all'" values="'oph_all'">hierarchy</argument>
	<argument type="double" mandatory="no" default="2" minvalue="0">order</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_EXTEND_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_extend" version="1.0">
    <info>
        <abstract>[Behaviour]
Return an array obtained by concatenating input array more times. Append mode concatenates arrays in sequence, Interlace mode replies each element in place one by one.

[Parameters]
- input measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- output measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- measure : list of input measure.
- number : number of replies.
- mode : use 'a' to concatenate input cubes (default), use 'i' to interlace input cubes.

[Return type]
Binary-array.

[Examples]
Concatenate input array four times.
oph_extend(&apos;OPH_DOUBLE&apos;,&apos;OPH_DOUBLE&apos;,measure,4)</abstract>
        <author>CMCC Foundation</author>
        <category>Core Array</category>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
        <operation type="simple"/>
    </info>
    <args>
		<argument type="oph_type" mandatory="yes" default="'oph_double'" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">input measure type</argument>
		<argument type="oph_type" mandatory="yes" default="'oph_double'" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">output measure type</argument>
		<argument type="binary-array" mandatory="yes">measure</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1">number</argument>
		<argument type="string" mandatory="no" default="'a'" values="'a'|'i'">mode</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_GSL_IFFT_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_gsl_ifft" version="1.0">
    <info>
        <abstract>[Behaviour]
Compute the inverse Fast Fourier Transform of a measure array.
Measures must be OPH_COMPLEX_DOUBLEs as returned by oph_gsl_fft.

[Parameters]
- input measure type : Ophidia typing. Supported type is &apos;oph_complex_double&apos;.
- output measure type : Ophidia typing. Supported type is &apos;oph_complex_double&apos;.
- measure : input measure.

[Return type]
Binary-array.

[Examples]
Compute the original signal through the IFFT of the input coefficients.
oph_gsl_ifft(&apos;OPH_COMPLEX_DOUBLE&apos;,&apos;OPH_COMPLEX_DOUBLE&apos;,measure)</abstract>
        <author>CMCC Foundation</author>
        <category>Transformation</category>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
        <operation type="simple"/>
    </info>
    <args>
		<argument type="oph_type" mandatory="yes" values="'oph_complex_double'">input measure type</argument>
		<argument type="oph_type" mandatory="yes" values="'oph_complex_double'">output measure type</argument>
		<argument type="binary-array" mandatory="yes">measure</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_BIT_SEQUENCE_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_bit_sequence" version="1.0">
    <info>
        <abstract>[Behaviour]
Evalute a number of statistics on bit_sequences of a bit array.
        
[Parameters]
- input data type : not used.
- output measure type : Ophidia typing. Supported types are:
					&apos;oph_double&apos;;
					&apos;oph_float&apos;;
					&apos;oph_long&apos;;
					&apos;oph_int&apos;;
					&apos;oph_short&apos;;
					&apos;oph_byte&apos;.
- measure : input measure.
- mask : possible values are
         -- 0000 : invalid
         -- 1xxx : number of bit sequences
         -- x1xx : mean size of bit sequence
         -- xx1x : maximum size of bit sequence
         -- xxx1 : maximum size of bit sequence
- value : value of bit composing the sequence, 0 or 1 (default).
        
[Return type]
Binary-array.
        
[Examples]
Count the number of bit sequences.
oph_bit_sequence(&apos;&apos;,&apos;OPH_LONG&apos;,measure,&apos;1&apos;)</abstract>
        <author>CMCC</author>
        <creationdate>19/12/2016</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
	<operation type="reduce"/>
    </info>
    <args>
	<argument type="oph_type" mandatory="yes">input data type</argument>
	<argument type="oph_type" mandatory="yes" values="'oph_double'|'oph_float'|'oph_int'|'oph_long'|'oph_short'|'oph_byte'">output measure type</argument>
	<argument type="bit-array" mandatory="yes">measure</argument>
	<argument type="string" mandatory="no" default="1111">mask</argument>
	<argument type="bit" mandatory="no" default="1" values="0|1">value</argument>
    </args>
</primitive>

=== OphidiaBigData/ophidia-analytics-framework/etc/primitives_xml/OPH_UNCOMPRESS_primitive_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE primitive SYSTEM "ophidiaprimitive.dtd">
<primitive name="oph_uncompress" version="1.0">
    <info>
        <abstract>[Behaviour]
Uncompresses the input array using ZLIB library (Same method used by MySQL). 

[Parameters]
- input measure type : not used.
- output measure type : not used.
- measure : compressed input measure.

[Return type]
Binary-array.

[Examples]
Uncompress input measures.
oph_uncompress(&apos;&apos;,&apos;&apos;,measure)</abstract>
        <author>CMCC Foundation</author>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <return type="binary-array" />
	<operation type="simple"/>
    </info>
    <args>
	<argument type="oph_type" mandatory="yes">input measure type</argument>
        <argument type="oph_type" mandatory="yes">output measure type</argument>
	<argument type="binary-array" mandatory="yes">measure</argument>
    </args>
</primitive>
