=== OphidiaBigData/ophidia-analytics-framework/etc/ophidia_dtd/ophidiaoperator.dtd
<!-- DTD for Ophidia operators -->

<!ELEMENT operator (info,args)>
<!ATTLIST operator name CDATA #REQUIRED>
<!ATTLIST operator version CDATA #REQUIRED>

<!ELEMENT info (abstract,author,creationdate?,license?,permission?)>

<!ELEMENT abstract (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT creationdate (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ATTLIST license url CDATA #REQUIRED>
<!ELEMENT permission (#PCDATA)>

<!ELEMENT args (argument*)>

<!ELEMENT argument (#PCDATA)>
<!ATTLIST argument type (char|string|int|real|date) #REQUIRED>
<!ATTLIST argument minvalue CDATA #IMPLIED>
<!ATTLIST argument maxvalue CDATA #IMPLIED>
<!ATTLIST argument default CDATA #IMPLIED>
<!ATTLIST argument values CDATA #IMPLIED>
<!ATTLIST argument mandatory (yes|no) "yes">

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_RANDCUBE2_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_RANDCUBE2" version="1.0">
    <info>
        <abstract>[Type]
Data Process.
        	
[Behaviour]
It creates a new datacube with random data and dimensions. Works only with Ophidia I/O server.

[Parameters]
- cwd : absolute path corresponding to the current working directory.
- host_partition : name of I/O host partition used to store data. By default the first available host partition will be used.
- ioserver : type of I/O server used to store data.
             Only possible values is: &quot;ophidiaio_memory&quot; (default)
- schedule : scheduling algorithm. The only possible value is 0,
		   for a static linear block distribution of resources.
- nhost : number of output hosts. With default value (&apos;0&apos;) all host available in the host partition are used.
- nfrag : number of fragments per database.
- ntuple : number of tuples per fragment.
- run : If set to &apos;no&apos; the operator simulates the creation and computes the fragmentation parameters 
		that would be used, else if set to &apos;yes&apos; the actual cube creation is executed.
- measure : name of the measure used in the datacube.
- measure_type : type of measures. Possible values are &quot;double&quot;, &quot;float&quot; or &quot;int&quot;
- exp_ndim : used to specify how many dimensions in dim argument, starting from the first one,
				 must be considered as explicit dimensions. NOTE: the new datacube must have at least 
				one implicit dimension, hence the total number of dimensions is bigger or equal 
				than exp_ndim +1.
- dim: name of the dimension. 
				Multiple-value field: list of dimensions separated by &quot;|&quot; can be provided  
- concept_level: concept level short name (must be a single char). Default value is &quot;c&quot;
				Multiple-value field: list of concept levels separated by &quot;|&quot; can be provided. 
- dim_size: size of random dimension.
				Multiple-value field: list of dimension sizes separated by &quot;|&quot; can be provided. 
- compressed : if set to &quot;yes&quot;, new data will be compressed.
			 With &quot;no&quot; (default), data will be inserted without compression.
- grid: optional argument used to identify the grid of dimensions to be used (if the grid already exists) 
             or the one to be created (if the grid has a new name). If it isn't specified, no grid will be used.
- description : additional description to be associated with the output cube.
- output_path : optional folder where the output cube will be stored; by default the cube is saved in current working directory.
- algorithm : it can be used to specify the type of emulation schema used to generate data. By default values are sampled indipendently from a uniform distribution in the range [0, 1000]. If "temperatures" is used, then values are generated with a first order auto-regressive model to be consistent with temperature values (in Celsius).
- dim_type: types of the dimensions. Default value is &quot;double&quot; for all the dimensions.
            Multiple-value field: list of types separated by &quot;|&quot; can be provided.
- hierarchy: concept hierarchy name of the dimensions. Default value is &quot;oph_base&quot;
             Multiple-value field: list of concept hierarchies separated by &quot;|&quot; can be provided, the explicit dimensions first.
- vocabulary: optional argument used to indicate a vocabulary (name of set of keys) to be associated with metadata.
- base_time: in case of time hierarchy, it indicates the base time of the dimension. Default value is 1900-01-01.
- units: in case of time hierarchy, it indicates the units of the dimension. Possible values are: s, m, h, 3, 6, d.
- calendar: in case of time hierarchy, it indicates the calendar type. Possible values are:
            -- standard (default)
            -- gregorian
            -- proleptic_gregorian
            -- julian
            -- 360_day
            -- no_leap
            -- all_leap
            -- user_defined
- month_lengths: in case of time dimension and user-defined calendar, it indicates the sizes of each month in days.
                 There must be 12 positive integers separated by commas. Default is &apos;31,28,31,30,31,30,31,31,30,31,30,31&apos;.
- leap_year: in case of time dimension and user-defined calendar, it indicates the first leap year. By default it is set to 0.
- leap_month: in case of time dimension and user-defined calendar, it indicates the leap month. By default it is set to 2 (i.e. February).
- policy : rule to select how data are distribuited over hosts:
           -- &apos;rr&apos; hosts are ordered on the basis of the number of cubes stored by it (default);
           -- &apos;port&apos; hosts are ordered on the basis of port number.
     
[System parameters]
- exec_mode : operator execution mode. Possible values are async (default) for
              asynchronous mode, sync for synchronous mode with json-compliant output.
- ncores : number of parallel processes to be used (min. 1).       
- nthreads : number of parallel threads per process to be used (min. 1).
- sessionid : session identifier used server-side to manage sessions and jobs.
              Usually users don't need to use/modify it, except when it is necessary
              to create a new session or switch to another one.
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
                  randcube : show operator's output PID as text in case "run" is "yes", else the parameter check is shown.

[Examples]
Generate a random compressed data cube with 1 host, 8 fragments/db, 10 tuples/fragment, 10 elements/tuple
with &apos;pressure&apos; measure and &apos;lat&apos;, &apos;lon&apos; and &apos;time&apos; dimensions:
OPH_TERM: oph_randcube2 nhost=1;nfrag=8;ntuple=10;measure=Pressure;measure_type=double;exp_ndim=2;dim=lat|lon|time;concept_level=c|c|d;dim_size=16|10|10;compressed=yes;
SUBMISSION STRING: &quot;operator=oph_randcube2;nhost=1;nfrag=8;ntuple=10;measure=Pressure;measure_type=double;exp_ndim=2;dim=lat|lon|time;concept_level=c|c|d;dim_size=16|10|10;compressed=yes;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Data Import/Export</category>
        <creationdate>04/10/2018</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>write</permission>
    </info>
    <args>
		<argument type="string" mandatory="no" default="null">sessionid</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1">ncores</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1">nthreads</argument>
		<argument type="string" mandatory="no" default="async" values="async|sync">exec_mode</argument>
		<argument type="string" mandatory="yes">cwd</argument>
		<argument type="string" mandatory="no" default="auto">host_partition</argument>
		<argument type="string" mandatory="no" default="ophidiaio_memory" values="ophidiaio_memory">ioserver</argument>
		<argument type="int" mandatory="no" default="0" values="0">schedule</argument>
		<argument type="int" mandatory="no" minvalue="0" default="0">nhost</argument>
		<argument type="string" mandatory="no" default="yes" values="yes|no">run</argument>
		<argument type="int" mandatory="yes" minvalue="1">nfrag</argument>
		<argument type="int" mandatory="yes" minvalue="1">ntuple</argument>
		<argument type="string" mandatory="yes">measure</argument>
		<argument type="string" mandatory="yes" values="double|float|int|long|short|byte">measure_type</argument>
		<argument type="int" mandatory="yes" minvalue="1">exp_ndim</argument>
		<argument type="string" mandatory="yes" multivalue="yes">dim</argument>
		<argument type="string" mandatory="no" default="c" multivalue="yes">concept_level</argument>
		<argument type="string" mandatory="yes" multivalue="yes">dim_size</argument>
		<argument type="string" mandatory="no" default="no" values="yes|no">compressed</argument>
		<argument type="string" mandatory="no" default="-">grid</argument>
		<argument type="string" mandatory="no" default="-">description</argument>
		<argument type="string" mandatory="no" default="-">output_path</argument>
		<argument type="string" mandatory="no" default="double" values="double|float|int|long|short|byte" multivalue="yes">dim_type</argument>
		<argument type="string" mandatory="no" default="oph_base" multivalue="yes">hierarchy</argument>
		<argument type="string" mandatory="no" default="CF">vocabulary</argument>
		<argument type="string" mandatory="no" default="1900-01-01 00:00:00">base_time</argument>
		<argument type="string" mandatory="no" default="d" values="s|m|h|3|6|d">units</argument>
		<argument type="string" mandatory="no" default="standard" values="standard|gregorian|proleptic_gregorian|julian|360_day|no_leap|all_leap|user_defined">calendar</argument>
		<argument type="string" mandatory="no" default="31,28,31,30,31,30,31,31,30,31,30,31">month_lengths</argument>
		<argument type="int" mandatory="no" default="0" minvalue="0">leap_year</argument>
		<argument type="int" mandatory="no" default="2" minvalue="1" maxvalue="12">leap_month</argument>
		<argument type="string" mandatory="no" default="rr" values="rr|port">policy</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|randcube2">objkey_filter</argument>
		<argument type="string" mandatory="no" default="default" values="default|temperatures">algorithm</argument>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_TASKS_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_TASKS" version="1.0">
    <info>
        <abstract>[Type]
Metadata Access.

[Behaviour]
It shows information about executed tasks. 
Default arguments allow to show all the tasks executed. 
If a container is given, then only tasks that involve the container are shown.
Optional filters on operation and datacube PID can also be used.
Any filter can use SQL wildcards (%, _, etc.)

[Parameters]
- cube_filter : optional filter on the name of input/output datacubes. The name must be in PID format.
				Default value is &quot;all&quot;.		
- operator_filter : optional filter on the name of the operators implied in tasks.
				    Default value is &quot;all&quot;.
- path : optional filter on absolute/relative path. Path is expanded so it can also contain 
		 &apos;.&apos; and &apos;..&apos;  
 		 It is only considered when container_filter is specified.
- cwd : absolute path corresponding to the current working directory, necessary to correctly parse paths.
        All resolved paths must be associated to the calling session, so they should contain &quot;/&lt;session-code&gt;&quot;.
		It is only considered when container_filter is specified.
- recursive : specifies if the search is done recursively or not. 
              The argument is considered only for the first three levels and may have the following values:
              -- no : research only in current path (default)
              -- yes : research recursively starting from current path.
- container: optional filter on containers. The argument is considered only inside 
			the specified path. Default is &quot;all&quot;.

[System parameters]    
- exec_mode : operator execution mode. Possible values are async (default) for
              asynchronous mode, sync for synchronous mode with json-compliant output.
- ncores : number of parallel processes to be used (min. 1).
           This operator is not parallel, so the only possible value is 1.
- sessionid : session identifier used server-side to manage sessions and jobs.
              Usually users don't need to use/modify it, except when it is necessary
              to create a new session or switch to another one.
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
                  tasks : show a list of tasks submitted previously.

[Examples]
Show information about all tasks :
OPH_TERM: oph_tasks cube_filter=all;operator_filter=all;
SUBMISSION STRING: &quot;operator=oph_tasks;cube_filter=all;operator_filter=all;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Metadata</category>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>read</permission>
    </info>
    <args>
		<argument type="string" mandatory="no" default="all">cube_filter</argument>
		<argument type="string" mandatory="no" default="all">operator_filter</argument>
		<argument type="string" mandatory="no" default="-">path</argument>
		<argument type="string" mandatory="yes">cwd</argument>
		<argument type="string" mandatory="no" default="no" values="yes|no">recursive</argument>
		<argument type="string" mandatory="no" default="all">container</argument>
		<argument type="string" mandatory="no" default="async" values="async|sync">exec_mode</argument>
		<argument type="string" mandatory="no" default="null">sessionid</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1" maxvalue="1">ncores</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|tasks">objkey_filter</argument>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_INPUT_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_INPUT" version="1.0">
    <info>
        <abstract>[Type]
Metadata access.

[Behaviour]
Send commands or data to an interactive task (&quot;OPH_WAIT&quot;). Set parameters in a workflow environment.
      
[Parameters]
- id : workflow identifier. By default the hosting workflow is selected. The target workflow must have been submitted in the same session.
- taskname : name of the intereactive task. By default it is set to &quot;Task 0&quot; and it can be automatically set to the interactive task of target workflow if it unique.
- action : name of the command to be sent to the interactive task. Use:
	&quot;continue&quot; to unlock the task (default);
	&quot;abort&quot; to abort the task;
	&quot;wait&quot; in case of no action.
- key : name of the parameter. It should comply with IEEE Std 1003.1-2001 conventions, unless brackets {} are adopted to refer it.
- value : value of the parameter. By default it will se to 1. It can be accessed with @key or @{key}.

[System parameters]
- save : set to &quot;yes&quot; (default) in case output has to be saved remotely.

[Examples]
Set the parameter &quot;var&quot; to 10 for task &quot;example&quot; in workflow 1 and unblock the task:
OPH_TERM: oph_input key=var;value=10;id=1;taskname=example;
SUBMISSION STRING: &quot;operator=oph_input;key=var;value=10;id=1;taskname=example;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Workflow Management</category>
        <creationdate>02/09/2016</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>write</permission>
    </info>
    <args>
		<argument type="int" mandatory="no" default="@OPH_WORKFLOW_ID" minvalue="0">id</argument>
		<argument type="string" mandatory="no" default="Task 0">taskname</argument>
		<argument type="string" mandatory="no" default="continue" values="continue|abort|wait">action</argument>
		<argument type="string" mandatory="no" default="-" multivalue="yes">key</argument>
		<argument type="string" mandatory="no" default="-" multivalue="yes">value</argument>
		<argument type="string" mandatory="no" default="yes" values="yes|no">save</argument>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_EXPLORECUBE_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_EXPLORECUBE" version="1.0">
    <info>
        <abstract>[Type]
Data Process.

[Behaviour]
It prints the data stored into a datacube, possibly subset along its dimensions.
Dimension values are used as input filters for subsetting.

[Parameters]
- cube : name of the input datacube. The name must be in PID format.
- schedule : scheduling algorithm. The only possible value is 0,
			for a static linear block distribution of resources.	   
- subset_dims : dimension names of the datacube used for the subsetting.
			Multiple-value field: list of dimensions separated by &quot;|&quot; can be provided  
			Must be the same number of &quot;subset_filter&quot; 
- subset_filter : enumeration of comma-separated elementary filters (1 series of filters for each dimension).
                  Multiple-value field: list of filters separated by &quot;|&quot; can be provided; it must be the same number of &quot;subset_dims&quot;
                  In case &quot;subset_type&quot; is &quot;index&quot; a filter can be expressed as
                  -- index : select a single value, specified by its index;
                  -- start_index:stop_index : select elements from start_index to stop_index;
                  -- start_index:stride:stop_index : select elements from start_index to stop_index with a step of stride.
                  Indexes are integers from 1 to the dimension size. It can be also used &quot;end&quot; to specify the index of the last element.
                  Example: subset_dims=lat|lon;subset_filter=1:10|20:end;
                  In case &quot;subset_type&quot; is &quot;coord&quot; a filter can be expressed as
                  -- value : select a specific value;
                  -- start_value:stop_value : select elements from start_value to stop_value; return an error if this set is empty.
                  Values should be numbers. Example: subset_dims=lat|lon;subset_filter=35:45|15:20;
                  For time dimensions the option &quot;time_filter&quot; can be enabled, so that the following date formats can be also used:
                  -- yyyy
                  -- yyyy-mm
                  -- yyyy-mm-dd
                  -- yyyy-mm-dd hh
                  -- yyyy-mm-dd hh:mm
                  -- yyyy-mm-dd hh:mm:ss
                  In this case, interval bounds must be separated with &quot;_&quot;.
                  Refer to a season using the corresponding code: DJF for winter, MAM for spring, JJA for summer or SON for autumn.
- subset_type : if set to &quot;index&quot; (default), the subset_filter is considered on dimension index. 
                With &quot;coord&quot;, filter is considered on dimension values.
- time_filter : enable filters using dates for time dimensions; enabled by default.
- limit_filter : optional filter on the maximum number of rows.
- show_id : if &quot;no&quot; (default), it won't show fragment row ID.
			With &quot;yes&quot;, it will also show the fragment row ID.
- show_index : if &quot;no&quot; (default), it won't show dimension ids.
			With &quot;yes&quot;, it will also show the dimension id next to the value.
- show_time : if &quot;no&quot; (default), the values of time dimension are shown as numbers.
			With &quot;yes&quot;, the values are converted as a string with date and time.
- level : with 1 (default) only measure values are shown, if it is set to &quot;2&quot; the dimension values are also returned.
- output_path : absolute path of the JSON Response. By default JSON Response is saved in core environment.
- output_name : filename of the JSON Response. The default value is the PID of the input datacube.
                File is saved provided that &quot;output_path&quot; is set.
- cdd : absolute path corresponding to the current directory on data repository.
- base64 : if &quot;no&quot; (default), dimension values are returned as strings (with possible trucantion errors).
			With &quot;yes&quot;, raw dimension values are returned as base64-coded strings.

[System parameters]    
- exec_mode : operator execution mode. Possible values are async (default) for
              asynchronous mode, sync for synchronous mode with json-compliant output.
- ncores : number of parallel processes to be used (it must be 1).
- sessionid : session identifier used server-side to manage sessions and jobs.
              Usually users don't need to use/modify it, except when it is necessary
              to create a new session or switch to another one.
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
		  explorecube_data : show the content of a cube.
		  explorecube_summary : show the number of rows to be extracted.
		  explorecube_dimvalues : show the values of the dimensions of output cube.

[Examples]       
Print the subset consisting of values 1 through 10 of dimension &quot;lat&quot; and 20 through 30 of dimension &quot;lon&quot; :
OPH_TERM: oph_explorecube cube=http://www.example.com/1/1;subset_dims=lat|lon;subset_filter=1:10|20:30;
SUBMISSION STRING: &quot;operator=oph_explorecube;cube=http://www.example.com/1/1;subset_dims=lat|lon;subset_filter=1:10|20:30;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Data Import/Export</category>
        <creationdate>27/02/2014</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>read</permission>
    </info>
    <args>
		<argument type="string" mandatory="yes" multivalue="yes">cube</argument>
		<argument type="int" mandatory="no" default="0" values="0">schedule</argument>
		<argument type="int" mandatory="no" default="100" minvalue="0" maxvalue="10000">limit_filter</argument>
		<argument type="string" mandatory="no" default="none" multivalue="yes">subset_dims</argument>
		<argument type="string" mandatory="no" default="all" multivalue="yes">subset_filter</argument>
		<argument type="string" mandatory="no" default="yes" values="yes|no">time_filter</argument>
		<argument type="string" mandatory="no" default="index" values="index|coord">subset_type</argument>
		<argument type="string" mandatory="no" default="no" values="yes|no">show_index</argument>
		<argument type="string" mandatory="no" default="no" values="yes|no">show_id</argument>
		<argument type="string" mandatory="no" default="no" values="yes|no">show_time</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1" maxvalue="2" values="1|2">level</argument>
		<argument type="string" mandatory="no" default="default">output_path</argument>
		<argument type="string" mandatory="no" default="default">output_name</argument>
		<argument type="string" mandatory="no" default="/">cdd</argument>
		<argument type="string" mandatory="no" default="no" values="yes|no">base64</argument>
		<argument type="string" mandatory="no" default="null">sessionid</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1" maxvalue="1">ncores</argument>
		<argument type="string" mandatory="no" default="async" values="async|sync">exec_mode</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|explorecube_data|explorecube_summary|explorecube_dimvalues">objkey_filter</argument>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_SCRIPT_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_SCRIPT" version="1.0">
    <info>
        <abstract>[Type]
General.

[Behaviour]
It executes a bash script. The script can eventually use the env var OPH_SCRIPT_SESSION_PATH passed by the operator and pointing to &lt;oph_web_server_location&gt;/sessions/&lt;session_code&gt;/export/misc.

[Parameters]
- script : name of the script to be executed (when requested &quot;./&quot; has to be included)
- args : list of pipe-separated arguments to be passed to the script
- stdout : file where stdout will be redirected (appended) or &quot;stdout&quot; for no redirection
- stderr : file where stderr will be redirected (appended) or &quot;stderr&quot; for no redirection
        
[System parameters]    
- exec_mode : operator execution mode. Possible values are async (default) for
              asynchronous mode, sync for synchronous mode with json-compliant output.
- ncores : number of parallel processes to be used (min. 1).
           This operator is not parallel, so the only possible value is 1.
- sessionid : session identifier used server-side to manage sessions and jobs.
              Usually users don't need to use/modify it, except when it is necessary
              to create a new session or switch to another one.
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
                  script : show the full command that was launched.
        
[Examples]
Execute the script &quot;./test.sh var1 var2&quot; without redirecting stdout and stderr:
OPH_TERM: oph_script script=./test.sh;args=var1|var2;
SUBMISSION STRING: &quot;operator=oph_script;script=./test.sh;args=var1|var2;&quot;</abstract>
        <author>CMCC Foundation</author>
        <creationdate>10/08/2014</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
	<permission>execute</permission>
    </info>
    <args>
        <argument type="string" mandatory="yes">script</argument>
        <argument type="string" mandatory="no" default=" ">args</argument>
        <argument type="string" mandatory="no" default="stdout">stdout</argument>
        <argument type="string" mandatory="no" default="stderr">stderr</argument>
        <argument type="string" mandatory="no" default="async" values="async|sync">exec_mode</argument>
        <argument type="string" mandatory="no" default="null">sessionid</argument>
        <argument type="int" mandatory="no" default="1" minvalue="1" maxvalue="1">ncores</argument>
	    <argument type="string" mandatory="no" default="all" values="all|none|script">objkey_filter</argument>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_DELETE_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_DELETE" version="1.0">
    <info>
        <abstract>[Type]
Data Process.
            
[Behaviour]
It removes a datacube.

[Parameters]
- cube : name of the input datacube. The name must be in PID format.
- schedule : scheduling algorithm. The only possible value is 0,
		   for a static linear block distribution of resources.

[System parameters]
- exec_mode : operator execution mode. Possible values are async (default) for
              asynchronous mode, sync for synchronous mode with json-compliant output.
- ncores : number of parallel processes to be used (min. 1).
- nthreads : number of parallel threads per process to be used (min. 1).
- sessionid : session identifier used server-side to manage sessions and jobs.
              Usually users don't need to use/modify it, except when it is necessary
              to create a new session or switch to another one.
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
		delete : no output.

[Examples]
Remove datacube identified by the PID &quot;http://www.example.com/1/1&quot; :
OPH_TERM: oph_delete cube=http://www.example.com/1/1;
SUBMISSION STRING: &quot;operator=oph_delete;cube=http://www.example.com/1/1;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Virtual File System</category>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>write</permission>
    </info>
    <args>
		<argument type="string" mandatory="no" default="async" values="async|sync">exec_mode</argument>
		<argument type="string" mandatory="no" default="null">sessionid</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1">ncores</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1">nthreads</argument>
		<argument type="string" mandatory="yes" multivalue="yes">cube</argument>
		<argument type="int" mandatory="no" default="0" values="0">schedule</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|delete">objkey_filter</argument>
    </args>
</operator>
