=== OphidiaBigData/ophidia-analytics-framework/etc/ophidia_dtd/ophidiaoperator.dtd
<!-- DTD for Ophidia operators -->

<!ELEMENT operator (info,args)>
<!ATTLIST operator name CDATA #REQUIRED>
<!ATTLIST operator version CDATA #REQUIRED>

<!ELEMENT info (abstract,author,creationdate?,license?,permission?)>

<!ELEMENT abstract (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT creationdate (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ATTLIST license url CDATA #REQUIRED>
<!ELEMENT permission (#PCDATA)>

<!ELEMENT args (argument*)>

<!ELEMENT argument (#PCDATA)>
<!ATTLIST argument type (char|string|int|real|date) #REQUIRED>
<!ATTLIST argument minvalue CDATA #IMPLIED>
<!ATTLIST argument maxvalue CDATA #IMPLIED>
<!ATTLIST argument default CDATA #IMPLIED>
<!ATTLIST argument values CDATA #IMPLIED>
<!ATTLIST argument mandatory (yes|no) "yes">

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_CREATECONTAINER_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_CREATECONTAINER" version="1.0">
    <info>
        <abstract>[Type]
Data Process.

[Behaviour]
It creates an empty container.

[Parameters]
- container : name of the output container. It must be unique among folders and visible containers within the same parent folder.
- cwd : absolute path corresponding to the current working directory,
        used to select the folder where the container will be created.
- dim: names of the dimensions allowed. Multiple-value field: list of dimensions separated by &quot;|&quot; can be provided.
- dim_type: types of the dimensions. Default value is &quot;double&quot; for all the dimensions.
            Multiple-value field: list of types separated by &quot;|&quot; can be provided.
- hierarchy: concept hierarchy name of the dimensions. Default value is &quot;oph_base&quot;
             Multiple-value field: list of concept hierarchies separated by &quot;|&quot; can be provided.
- base_time: in case of time hierarchy, it indicates the base time of the dimension. Default value is 1900-01-01.
- units: in case of time hierarchy, it indicates the units of the dimension. Possible values are: s, m, h, 3, 6, d.
- calendar: in case of time hierarchy, it indicates the calendar type. Possible values are:
            -- standard (default)
            -- gregorian
            -- proleptic_gregorian
            -- julian
            -- 360_day
            -- 365_day
            -- 366_day
            -- no_leap (equivalent to 365_day)
            -- all_leap  (equivalent to 366_day)
            -- user_defined
- month_lengths: in case of time dimension and user-defined calendar, it indicates the sizes of each month in days.
            There must be 12 positive integers separated by commas. Default is &apos;31,28,31,30,31,30,31,31,30,31,30,31&apos;.
- leap_year: in case of time dimension and user-defined calendar, it indicates the first leap year. By default it is set to 0.
- leap_month: in case of time dimension and user-defined calendar, it indicates the leap month. By default it is set to 2 (i.e. February).
- vocabulary: optional argument used to indicate a vocabulary (name of set of keys) to be used 
			  to associate metadata to the container.
- compressed : if &quot;yes&quot;, new data will be compressed.
			   With &quot;no&quot; (default), data will be inserted without compression.
- description : additional description to be associated with the output container.

[System parameters]    
- exec_mode : operator execution mode. Possible values are async (default) for
              asynchronous mode, sync for synchronous mode with json-compliant output.
- ncores : number of parallel processes to be used (min. 1).
           This operator is not parallel, so the only possible value is 1.
- sessionid : session identifier used server-side to manage sessions and jobs.
              Usually users don't need to use/modify it, except when it is necessary
              to create a new session or switch to another one.
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
                  createcontainer : show operator's output PID as text.

[Examples]       
Create a new container &apos;container1&apos; with dimensions lat, lon and time into folder &apos;/folder&apos;:
OPH_TERM:: oph_createcontainer container=container1;cwd=/folder;dim=lat|lon|time;dim_type=double|double|double;hierarchy=oph_base|oph_base|oph_time;
SUBMISSION STRING: &quot;operator=oph_createcontainer;container=container1;cwd=/session-code1;dim=lat|lon|time;dim_type=double|double|double;hierarchy=oph_base|oph_base|oph_time;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Virtual File System</category>
        <creationdate>24/09/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>write</permission>
    </info>
    <args>
		<argument type="string" mandatory="no" default="null">sessionid</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1" maxvalue="1">ncores</argument>
		<argument type="string" mandatory="no" default="async" values="async|sync">exec_mode</argument>
		<argument type="string" mandatory="yes">container</argument>
		<argument type="string" mandatory="yes">cwd</argument>
		<argument type="string" mandatory="yes" multivalue="yes">dim</argument>
		<argument type="string" mandatory="no" default="double" values="double|float|int|long|short|byte" multivalue="yes">dim_type</argument>
		<argument type="string" mandatory="no" default="oph_base" multivalue="yes">hierarchy</argument>
		<argument type="string" mandatory="no" default="1900-01-01 00:00:00">base_time</argument>
		<argument type="string" mandatory="no" default="d" values="s|m|h|3|6|d">units</argument>
		<argument type="string" mandatory="no" default="standard" values="standard|gregorian|proleptic_gregorian|julian|360_day|365_day|366_day|no_leap|all_leap|user_defined">calendar</argument>
		<argument type="string" mandatory="no" default="31,28,31,30,31,30,31,31,30,31,30,31">month_lengths</argument>
		<argument type="int" mandatory="no" default="0" minvalue="0">leap_year</argument>
		<argument type="int" mandatory="no" default="2" minvalue="1" maxvalue="12">leap_month</argument>
		<argument type="string" mandatory="no" default="CF">vocabulary</argument>
		<argument type="string" mandatory="no" default="no" values="yes|no">compressed</argument>
		<argument type="string" mandatory="no" default="-">description</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|createcontainer">objkey_filter</argument>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_SHOWGRID_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_SHOWGRID" version="1.0">
    <info>
        <abstract>[Type]
Metadata Access.
            
[Behaviour]
It shows information about one or more grids related to the specified container.
            
[Parameters]
- container : name of the input container.
- grid : name of grid to show. With no name all grids are shown.
- dim : name of dimensions to show.
                   Multiple-value field: list of dimensions separated by &quot;|&quot; can be provided.
                   If not specified all dimensions are shown.
- show_index : if &quot;no&quot; (default), it won&apos;t show dimension ids.
               With &quot;yes&quot;, it will also show the dimension id next to the value.
- cwd : absolute path corresponding to the current working directory,
        necessary to correctly parse paths.
        All resolved paths must be associated to the calling session,
        so they should contain &quot;/&lt;session-code&gt;&quot;.
            
[System parameters]    
- exec_mode : operator execution mode. Possible values are async (default) for
              asynchronous mode, sync for synchronous mode with json-compliant output.
- ncores : number of parallel processes to be used (min. 1).
            This operator is not parallel, so the only possible value is 1.
- sessionid : session identifier used server-side to manage sessions and jobs.
             Usually users don't need to use/modify it, except when it is necessary
             to create a new session or switch to another one.
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
                  showgrid_diminfo : show the list of the dimensions associated with a container.
		  showgrid_dimvalues : show the values of the dimensions associated with a container.
		  showgrid_tip : show a help message.
            
[Examples]
Show the grid &apos;grid1&apos; related to container &apos;container1&apos; :
OPH_TERM: oph_showgrid container=container1;grid=grid1;cwd=/session-code1;
SUBMISSION STRING: &quot;operator=oph_showgrid;container=container1;grid=grid1;cwd=/session-code1;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Metadata</category>
        <creationdate>06/12/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>read</permission>
    </info>
    <args>
		<argument type="string" mandatory="yes">container</argument>
		<argument type="string" mandatory="no" default="all">grid</argument>
		<argument type="string" mandatory="no" default="all">dim</argument>
		<argument type="string" mandatory="no" default="no" values="yes|no">show_index</argument>
		<argument type="string" mandatory="yes">cwd</argument>
		<argument type="string" mandatory="no" default="async" values="async|sync">exec_mode</argument>
		<argument type="string" mandatory="no" default="null">sessionid</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1" maxvalue="1">ncores</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|showgrid_diminfo|showgrid_dimvalues|showgrid_tip">objkey_filter</argument>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_CUBESIZE_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_CUBESIZE" version="1.0">
    <info>
        <abstract>[Type]
Metadata Access.

[Behaviour]
It computes and displays the size of the input datacube.

[Parameters]
- cube : name of the input datacube. The name must be in PID format.
- schedule : scheduling algorithm. The only possible value is 0,
		     for a static linear block distribution of resources.
- byte_unit : measure unit used to show datacube size. The unit can be KB, 
            MB (default), GB, TB or PB
- algorithm : algorithm used to compute the size. Possible values are:
		        &quot;eurisitic&quot; (default) to estimate the size with an euristic method; 
              &quot;count&quot; to get the actual size of each fragment.


[System parameters]    
- exec_mode : operator execution mode. Possible values are async (default) for
              asynchronous mode, sync for synchronous mode with json-compliant output.
- ncores : number of parallel processes to be used (min. 1).
- sessionid : session identifier used server-side to manage sessions and jobs.
              Usually users don't need to use/modify it, except when it is necessary
              to create a new session or switch to another one.
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
                  cubesize : show cube size.

[Examples]
Compute the size of the datacube &quot;http://www.example.com/1/1&quot; :
OPH_TERM: oph_cubesize cube=http://www.example.com/1/1;
SUBMISSION STRING: &quot;operator=oph_cubesize;cube=http://www.example.com/1/1;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Metadata</category>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>read</permission>
    </info>
    <args>
		<argument type="string" mandatory="yes" multivalue="yes">cube</argument>
		<argument type="int" mandatory="no" default="0" minvalue="0" maxvalue="0" values="0">schedule</argument>
		<argument type="string" mandatory="no" default="async" values="async|sync">exec_mode</argument>
		<argument type="string" mandatory="no" default="MB" values="KB|MB|GB|TB|PB">byte_unit</argument>
		<argument type="string" mandatory="no" default="euristic" values="euristic|count">algorithm</argument>
		<argument type="string" mandatory="no" default="null">sessionid</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1">ncores</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|cubesize">objkey_filter</argument>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_INTERCUBE_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_INTERCUBE" version="1.0">
    <info>
        <abstract>[Type]
Data Process.

[Behaviour]
It executes an operation between two datacubes with the same fragmentation structure and
returns a new datacube as result of the specified operation applied element by element.

[Parameters]
- cube : name of the first operand datacube. The name must be in PID format.
         Considered only in case 'cubes' is not set.
- cube2 : name of the second operand datacube. The name must be in PID format.
          Considered only in case 'cubes' is not set.
- cubes : list of input cubes (only two are significant). The name must be in PID format.
          If set, the parameters 'cube' and 'cube2' are not considered.
- operation : type of inter-cube operation among these (default is sub):
              -- sum : sum correspondent elements one by one;
              -- sub : subtract the elements of the second operand from the first operand one by one (default);
              -- mul : multiply correspondent elements one by one;
              -- div : divide the elements of the first operand by the elements of the second operand one by one;
              -- abs : compute the modulus of corresponding elements one by one;
              -- arg : compute the phase of corresponding elements one by one;
              -- corr: compute the Pearson correlation coefficient row by row;
              -- mask: take all elements of cube corresponding to 1s in cube2,
                    remaining elements are set to 0 (int, byte, short or long) or NaN (float or double);
              -- max: return the maximum value between the corresponding elements one by one;
              -- min: return the minimum value between the corresponding elements one by one;
              -- arg_max: return 1 if the maximum value is associated with the first cube, 2 otherwise;
              -- arg_min: return 1 if the minimum value is associated with the first cube, 2 otherwise.
- missingvalue : value to be considered as missing value; by default it is NAN (for float and double).
- measure : name of the new measure resulting from the specified operation
- schedule : scheduling algorithm. The only possible value is 0,
		     for a static linear block distribution of resources.
- container : name of the container to be used to store the output cube; by default it is the container of the first cube.
- description : additional description to be associated with the output cube.
        
[System parameters]    
- exec_mode : operator execution mode. Possible values are async (default) for
              asynchronous mode, sync for synchronous mode with json-compliant output.
- ncores : number of parallel processes to be used (min. 1).
- sessionid : session identifier used server-side to manage sessions and jobs.
              Usually users don't need to use/modify it, except when it is necessary
              to create a new session or switch to another one.
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
                  intercube : show operator's output PID as text.
        
[Examples]       
Sum the datacubes identified by the PIDs &quot;http://www.example.com/1/1&quot; and &quot;http://www.example.com/1/2&quot; :
OPH_TERM: oph_intercube cube=http://www.example.com/1/1;cube2=http://www.example.com/1/2;operation=sum;output_measure=new_pressure;
SUBMISSION STRING: &quot;operator=oph_intercube;cube=http://www.example.com/1/1;cube2=http://www.example.com/1/2;operation=sum;output_measure=new_pressure;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Data Analysis</category>
        <creationdate>12/05/2014</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>write</permission>
    </info>
    <args>
		<argument type="string" mandatory="no" default="null">sessionid</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1">ncores</argument>
		<argument type="string" mandatory="no" default="async" values="async|sync">exec_mode</argument>
		<argument type="string" mandatory="no" multivalue="yes" default="-">cube</argument>
		<argument type="string" mandatory="no" default="-">cube2</argument>
		<argument type="string" mandatory="no" multivalue="yes" default="-">cubes</argument>
		<argument type="string" mandatory="no" default="sub" values="sum|sub|mul|div|abs|arg|corr|mask|max|min|arg_max|arg_min">operation</argument>
		<argument type="real" mandatory="no" default="NAN">missingvalue</argument>
		<argument type="string" mandatory="no" default="null">measure</argument>
		<argument type="int" mandatory="no" default="0" values="0">schedule</argument>
		<argument type="string" mandatory="no" default="-">container</argument>
		<argument type="string" mandatory="no" default="-">description</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|intercube">objkey_filter</argument>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_OPERATORS_LIST_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_OPERATORS_LIST" version="1.0">
    <info>
        <abstract>[Type]
Metadata Access.

[Behaviour]
It shows the list of all active operators.

[Parameters]
- operator_filter : optional filter on the name of the displayed operators,
                    with pattern *filter*.                
- limit_filter : optional filter on the maximum number of displayed operators.
                 Default value is 0, used to show all operators.

[System parameters]    
- exec_mode : operator execution mode. Possible values are async (default) for
              asynchronous mode, sync for synchronous mode with json-compliant output.
- ncores : number of parallel processes to be used (min. 1).
           This operator is not parallel, so the only possible value is 1.
- sessionid : session identifier used server-side to manage sessions and jobs.
              Usually users don't need to use/modify it, except when it is necessary
              to create a new session or switch to another one.
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
                  operators_list_list : show the operators list.
		  operators_list_tip: show a help message.

[Examples]
Get at most 10 operators with names containing the word &quot;list&quot; :
OPH_TERM: oph_operators_list operator_filter=list;limit_filter=10;
SUBMISSION STRING: &quot;operator=oph_operators_list;operator_filter=list;limit_filter=10;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Miscellaneous</category>
        <creationdate>27/07/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>read</permission>
    </info>
    <args>
		<argument type="string" mandatory="no" default="">operator_filter</argument>
		<argument type="int" mandatory="no" default="0" minvalue="0">limit_filter</argument>
		<argument type="string" mandatory="no" default="async" values="async|sync">exec_mode</argument>
		<argument type="string" mandatory="no" default="null">sessionid</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1" maxvalue="1">ncores</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|operators_list_list|operators_list_tip">objkey_filter</argument>
    </args>
</operator>

=== OphidiaBigData/ophidia-analytics-framework/etc/operators_xml/OPH_SEARCH_operator_1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE operator SYSTEM "ophidiaoperator.dtd">
<operator name="OPH_SEARCH" version="1.0">
    <info>
        <abstract>[Type]
Metadata Access.

[Behaviour]
It provides enhanced searching on metadata.
 
[Parameters]
- container_filter : zero, one or more filters on containers' names.
                     Filters could be any type of search string accepted by SQL,
                     with wildcards, OR-ed with pipes (filter1|filter2|...).
                     Mute this filter with the default value &quot;all&quot;.                  
- metadata_key_filter : zero, one or more filters on metadata keys.
                        Filters could be any type of search string accepted by SQL,
                        with wildcards, OR-ed with pipes (filter1|filter2|...).
                        Mute this filter with the default value &quot;all&quot;.                 
- metadata_value_filter : zero, one or more filters on metadata values.
                          Filters could be any type of search string accepted by SQL,
                          with wildcards, OR-ed with pipes (filter1|filter2|...).
                          Mute this filter with the default value &quot;all&quot;.
- path : absolute/relative path used as the starting point of the recursive search.
         If not specified or in case of &quot;-&quot; (default) the recursive search will start at the cwd.
- cwd : absolute path corresponding to the current working directory, necessary to correctly parse paths.
- recursive : specifies if the search is done recursively or not. 
              The argument is considered only for the first three levels and may have the following values:
              -- no : research only in current path (default)
              -- yes : research recursively starting from current path.

[System parameters]
- exec_mode : operator execution mode. Possible values are async (default) for
              asynchronous mode, sync for synchronous mode with json-compliant output.
- ncores : number of parallel processes to be used (min. 1).
            This operator is not parallel, so the only possible value is 1.
- sessionid : session identifier used server-side to manage sessions and jobs.
               Usually users don't need to use/modify it, except when it is necessary
               to create a new session or switch to another one.
- objkey_filter : filter on the output of the operator written to file (default=all => no filter, none => no output).
                  search : show metadata list.
 
 [Examples]       
 Get metadata with keys starting with &quot;key&quot; and values starting with &quot;http&quot; through a recursive search starting from &quot;/absolute/path&quot; :
 OPH_TERM: oph_search metadata_key_filter=key%;metadata_value_filter=http%;cwd=/absolute/path;
 SUBMISSION STRING: &quot;operator=oph_search;metadata_key_filter=key%;metadata_value_filter=http%;cwd=/absolute/path;&quot;</abstract>
        <author>CMCC Foundation</author>
        <category>Metadata</category>
        <creationdate>13/10/2013</creationdate>
        <license url="http://www.gnu.org/licenses/gpl.txt">GPLv3</license>
        <permission>read</permission>
    </info>
    <args>
		<argument type="string" mandatory="no" default="all" multivalue="yes">container_filter</argument>
		<argument type="string" mandatory="no" default="all" multivalue="yes">metadata_key_filter</argument>
		<argument type="string" mandatory="no" default="all" multivalue="yes">metadata_value_filter</argument>
		<argument type="string" mandatory="no" default="-">path</argument>
		<argument type="string" mandatory="yes">cwd</argument>
		<argument type="string" mandatory="no" default="no" values="yes|no">recursive</argument>
		<argument type="string" mandatory="no" default="async" values="async|sync">exec_mode</argument>
		<argument type="string" mandatory="no" default="null">sessionid</argument>
		<argument type="int" mandatory="no" default="1" minvalue="1" maxvalue="1">ncores</argument>
		<argument type="string" mandatory="no" default="all" values="all|none|search">objkey_filter</argument>
    </args>
</operator>
